/* Generated by scripts/generate-grade5-catalog.mjs. Do not edit by hand. */
export const grade5CharacterVisuals = {
  "鹭": {
    "src": "/illustrations/mnemonics/g5-u9e6d.svg",
    "label": "白鹭",
    "alt": "鹭字嵌在舒展翅尾的小鸟与轮廓像“路”的故事道具组成的学习插图中"
  },
  "嫌": {
    "src": "/illustrations/mnemonics/g5-u5acc.svg",
    "label": "嫌弃",
    "alt": "嫌字嵌在照料幼苗的人影与轮廓像“兼”的故事道具组成的学习插图中"
  },
  "嵌": {
    "src": "/illustrations/mnemonics/g5-u5d4c.svg",
    "label": "镶嵌",
    "alt": "嵌字嵌在高低相连的山峰与轮廓像“𣢟”的故事道具组成的学习插图中"
  },
  "匣": {
    "src": "/illustrations/mnemonics/g5-u5323.svg",
    "label": "匣子",
    "alt": "匣字嵌在轮廓像“匚”的故事道具与轮廓像“甲”的故事道具组成的学习插图中"
  },
  "嗜": {
    "src": "/illustrations/mnemonics/g5-u55dc.svg",
    "label": "嗜好",
    "alt": "嗜字嵌在方形传声窗与轮廓像“耆”的故事道具组成的学习插图中"
  },
  "宜": {
    "src": "/illustrations/mnemonics/g5-u5b9c.svg",
    "label": "适宜",
    "alt": "宜字嵌在安稳覆盖的屋顶与轮廓像“且”的故事道具组成的学习插图中"
  },
  "鹤": {
    "src": "/illustrations/mnemonics/g5-u9e64.svg",
    "label": "白鹤",
    "alt": "鹤字嵌在舒展翅尾的小鸟与轮廓像“隺”的故事道具组成的学习插图中"
  },
  "朱": {
    "src": "/illustrations/mnemonics/g5-u6731.svg",
    "label": "朱红",
    "alt": "朱字嵌在有横枝、直干和斜根的大树与轮廓像“未”的故事道具、轮廓像“㇒”的故事道具组成的学习插图中"
  },
  "框": {
    "src": "/illustrations/mnemonics/g5-u6846.svg",
    "label": "画框",
    "alt": "框字嵌在有横枝、直干和斜根的大树与轮廓像“匡”的故事道具组成的学习插图中"
  },
  "哨": {
    "src": "/illustrations/mnemonics/g5-u54e8.svg",
    "label": "口哨",
    "alt": "哨字嵌在方形传声窗与轮廓像“肖”的故事道具组成的学习插图中"
  },
  "恩": {
    "src": "/illustrations/mnemonics/g5-u6069.svg",
    "label": "恩惠",
    "alt": "恩字嵌在心形灯带与三点微光与轮廓像“因”的故事道具组成的学习插图中"
  },
  "韵": {
    "src": "/illustrations/mnemonics/g5-u97f5.svg",
    "label": "韵味",
    "alt": "韵字嵌在轮廓像“音”的故事道具与轮廓像“匀”的故事道具组成的学习插图中"
  },
  "亩": {
    "src": "/illustrations/mnemonics/g5-u4ea9.svg",
    "label": "半亩",
    "alt": "亩字嵌在轮廓像“亠”的故事道具与分成四格的田地组成的学习插图中"
  },
  "吩": {
    "src": "/illustrations/mnemonics/g5-u5429.svg",
    "label": "吩咐",
    "alt": "吩字嵌在方形传声窗与轮廓像“分”的故事道具组成的学习插图中"
  },
  "榨": {
    "src": "/illustrations/mnemonics/g5-u69a8.svg",
    "label": "榨油",
    "alt": "榨字嵌在有横枝、直干和斜根的大树与轮廓像“窄”的故事道具组成的学习插图中"
  },
  "榴": {
    "src": "/illustrations/mnemonics/g5-u69b4.svg",
    "label": "石榴",
    "alt": "榴字嵌在有横枝、直干和斜根的大树与轮廓像“留”的故事道具组成的学习插图中"
  },
  "矮": {
    "src": "/illustrations/mnemonics/g5-u77ee.svg",
    "label": "矮小",
    "alt": "矮字嵌在轮廓像“矢”的故事道具与轮廓像“委”的故事道具组成的学习插图中"
  },
  "播": {
    "src": "/illustrations/mnemonics/g5-u64ad.svg",
    "label": "播种",
    "alt": "播字嵌在伸出并发力的手臂与轮廓像“番”的故事道具组成的学习插图中"
  },
  "浇": {
    "src": "/illustrations/mnemonics/g5-u6d47.svg",
    "label": "浇水",
    "alt": "浇字嵌在三股清亮水流与轮廓像“尧”的故事道具组成的学习插图中"
  },
  "咐": {
    "src": "/illustrations/mnemonics/g5-u5490.svg",
    "label": "吩咐",
    "alt": "咐字嵌在方形传声窗与轮廓像“付”的故事道具组成的学习插图中"
  },
  "亭": {
    "src": "/illustrations/mnemonics/g5-u4ead.svg",
    "label": "茅亭",
    "alt": "亭字嵌在轮廓像“亠”的故事道具与轮廓像“丁”的故事道具组成的学习插图中"
  },
  "慕": {
    "src": "/illustrations/mnemonics/g5-u6155.svg",
    "label": "爱慕",
    "alt": "慕字嵌在轮廓像“⺗”的故事道具与轮廓像“莫”的故事道具、轮廓像“㣺”的故事道具组成的学习插图中"
  },
  "谈": {
    "src": "/illustrations/mnemonics/g5-u8c08.svg",
    "label": "谈论",
    "alt": "谈字嵌在从说话框飞出的短句与轮廓像“炎”的故事道具组成的学习插图中"
  },
  "箩": {
    "src": "/illustrations/mnemonics/g5-u7ba9.svg",
    "label": "箩筐",
    "alt": "箩字嵌在两簇竹叶与轮廓像“罗”的故事道具组成的学习插图中"
  },
  "杭": {
    "src": "/illustrations/mnemonics/g5-u676d.svg",
    "label": "杭州",
    "alt": "杭字嵌在有横枝、直干和斜根的大树与轮廓像“亢”的故事道具组成的学习插图中"
  },
  "懂": {
    "src": "/illustrations/mnemonics/g5-u61c2.svg",
    "label": "懂得",
    "alt": "懂字嵌在跳动的心形灯带与轮廓像“董”的故事道具组成的学习插图中"
  },
  "兰": {
    "src": "/illustrations/mnemonics/g5-u5170.svg",
    "label": "兰花",
    "alt": "兰字嵌在轮廓像“丷”的故事道具与轮廓像“三”的故事道具组成的学习插图中"
  },
  "婆": {
    "src": "/illustrations/mnemonics/g5-u5a46.svg",
    "label": "外婆",
    "alt": "婆字嵌在照料幼苗的人影与轮廓像“波”的故事道具组成的学习插图中"
  },
  "糕": {
    "src": "/illustrations/mnemonics/g5-u7cd5.svg",
    "label": "糕饼",
    "alt": "糕字嵌在米架和四散米粒与轮廓像“羔”的故事道具组成的学习插图中"
  },
  "饼": {
    "src": "/illustrations/mnemonics/g5-u997c.svg",
    "label": "糕饼",
    "alt": "饼字嵌在带盖的食器与轮廓像“并”的故事道具组成的学习插图中"
  },
  "浸": {
    "src": "/illustrations/mnemonics/g5-u6d78.svg",
    "label": "沉浸",
    "alt": "浸字嵌在三股清亮水流与完整物象组成的学习插图中"
  },
  "缠": {
    "src": "/illustrations/mnemonics/g5-u7f20.svg",
    "label": "纠缠",
    "alt": "缠字嵌在盘绕的细丝线与轮廓像“㢆”的故事道具组成的学习插图中"
  },
  "茶": {
    "src": "/illustrations/mnemonics/g5-u8336.svg",
    "label": "茶叶",
    "alt": "茶字嵌在成排草叶与花梗与完整物象组成的学习插图中"
  },
  "捡": {
    "src": "/illustrations/mnemonics/g5-u6361.svg",
    "label": "捡起",
    "alt": "捡字嵌在伸出并发力的手臂与轮廓像“佥”的故事道具组成的学习插图中"
  },
  "蔓": {
    "src": "/illustrations/mnemonics/g5-u8513.svg",
    "label": "蔓延",
    "alt": "蔓字嵌在成排草叶与花梗与轮廓像“曼”的故事道具组成的学习插图中"
  },
  "幽": {
    "src": "/illustrations/mnemonics/g5-u5e7d.svg",
    "label": "幽深",
    "alt": "幽字嵌在轮廓像“幺”的故事道具与高低相连的山峰、轮廓像“𢆶”的故事道具组成的学习插图中"
  },
  "悉": {
    "src": "/illustrations/mnemonics/g5-u6089.svg",
    "label": "熟悉",
    "alt": "悉字嵌在心形灯带与三点微光与轮廓像“釆”的故事道具组成的学习插图中"
  },
  "雏": {
    "src": "/illustrations/mnemonics/g5-u96cf.svg",
    "label": "雏鸟",
    "alt": "雏字嵌在轮廓像“隹”的故事道具与轮廓像“刍”的故事道具组成的学习插图中"
  },
  "哟": {
    "src": "/illustrations/mnemonics/g5-u54df.svg",
    "label": "哟",
    "alt": "哟字嵌在方形传声窗与轮廓像“约”的故事道具组成的学习插图中"
  },
  "柜": {
    "src": "/illustrations/mnemonics/g5-u67dc.svg",
    "label": "书柜",
    "alt": "柜字嵌在有横枝、直干和斜根的大树与轮廓像“巨”的故事道具组成的学习插图中"
  },
  "享": {
    "src": "/illustrations/mnemonics/g5-u4eab.svg",
    "label": "享受",
    "alt": "享字嵌在轮廓像“亠”的故事道具与被轻轻托住的孩子组成的学习插图中"
  },
  "陪": {
    "src": "/illustrations/mnemonics/g5-u966a.svg",
    "label": "陪伴",
    "alt": "陪字嵌在高低相接的土坡与轮廓像“咅”的故事道具组成的学习插图中"
  },
  "趴": {
    "src": "/illustrations/mnemonics/g5-u8db4.svg",
    "label": "趴下",
    "alt": "趴字嵌在脚印和落脚台与脚印和落脚台、轮廓像“八”的故事道具组成的学习插图中"
  },
  "睑": {
    "src": "/illustrations/mnemonics/g5-u7751.svg",
    "label": "眼睑",
    "alt": "睑字嵌在方框中的眼睛与轮廓像“佥”的故事道具组成的学习插图中"
  },
  "眸": {
    "src": "/illustrations/mnemonics/g5-u7738.svg",
    "label": "眼眸",
    "alt": "眸字嵌在方框中的眼睛与轮廓像“牟”的故事道具组成的学习插图中"
  },
  "咂": {
    "src": "/illustrations/mnemonics/g5-u5482.svg",
    "label": "咂嘴",
    "alt": "咂字嵌在方形传声窗与轮廓像“匝”的故事道具组成的学习插图中"
  },
  "汛": {
    "src": "/illustrations/mnemonics/g5-u6c5b.svg",
    "label": "汛期",
    "alt": "汛字嵌在三股清亮水流与轮廓像“卂”的故事道具组成的学习插图中"
  },
  "挽": {
    "src": "/illustrations/mnemonics/g5-u633d.svg",
    "label": "挽留",
    "alt": "挽字嵌在伸出并发力的手臂与轮廓像“免”的故事道具组成的学习插图中"
  },
  "间": {
    "src": "/illustrations/mnemonics/g5-u95f4.svg",
    "label": "间隔",
    "alt": "间字嵌在打开的双扇门与有中央光带的日轮组成的学习插图中"
  },
  "惰": {
    "src": "/illustrations/mnemonics/g5-u60f0.svg",
    "label": "懒惰",
    "alt": "惰字嵌在跳动的心形灯带与完整物象组成的学习插图中"
  },
  "衡": {
    "src": "/illustrations/mnemonics/g5-u8861.svg",
    "label": "平衡",
    "alt": "衡字嵌在轮廓像“行”的故事道具与完整物象组成的学习插图中"
  },
  "协": {
    "src": "/illustrations/mnemonics/g5-u534f.svg",
    "label": "协调",
    "alt": "协字嵌在轮廓像“十”的故事道具与轮廓像“办”的故事道具组成的学习插图中"
  },
  "绰": {
    "src": "/illustrations/mnemonics/g5-u7ef0.svg",
    "label": "绰绰有余",
    "alt": "绰字嵌在盘绕的细丝线与轮廓像“卓”的故事道具组成的学习插图中"
  },
  "洪": {
    "src": "/illustrations/mnemonics/g5-u6d2a.svg",
    "label": "洪水",
    "alt": "洪字嵌在三股清亮水流与轮廓像“共”的故事道具组成的学习插图中"
  },
  "访": {
    "src": "/illustrations/mnemonics/g5-u8bbf.svg",
    "label": "访问",
    "alt": "访字嵌在从说话框飞出的短句与轮廓像“方”的故事道具组成的学习插图中"
  },
  "鞋": {
    "src": "/illustrations/mnemonics/g5-u978b.svg",
    "label": "鞋子",
    "alt": "鞋字嵌在轮廓像“革”的故事道具与轮廓像“圭”的故事道具组成的学习插图中"
  },
  "隔": {
    "src": "/illustrations/mnemonics/g5-u9694.svg",
    "label": "间隔",
    "alt": "隔字嵌在高低相接的土坡与轮廓像“鬲”的故事道具组成的学习插图中"
  },
  "懒": {
    "src": "/illustrations/mnemonics/g5-u61d2.svg",
    "label": "懒惰",
    "alt": "懒字嵌在跳动的心形灯带与轮廓像“赖”的故事道具组成的学习插图中"
  },
  "稳": {
    "src": "/illustrations/mnemonics/g5-u7a33.svg",
    "label": "安稳",
    "alt": "稳字嵌在低垂的谷穗与轮廓像“急”的故事道具组成的学习插图中"
  },
  "免": {
    "src": "/illustrations/mnemonics/g5-u514d.svg",
    "label": "免得",
    "alt": "免字嵌在轮廓像“儿”的故事道具与轮廓像“⺈”的故事道具组成的学习插图中"
  },
  "璧": {
    "src": "/illustrations/mnemonics/g5-u74a7.svg",
    "label": "和氏璧",
    "alt": "璧字嵌在温润的玉石与轮廓像“辟”的故事道具组成的学习插图中"
  },
  "臣": {
    "src": "/illustrations/mnemonics/g5-u81e3.svg",
    "label": "大臣",
    "alt": "臣字嵌在轮廓像“匚”的故事道具与完整物象组成的学习插图中"
  },
  "强": {
    "src": "/illustrations/mnemonics/g5-u5f3a.svg",
    "label": "强迫",
    "alt": "强字嵌在绷紧的弓弦与轮廓像“虽”的故事道具组成的学习插图中"
  },
  "诺": {
    "src": "/illustrations/mnemonics/g5-u8bfa.svg",
    "label": "承诺",
    "alt": "诺字嵌在从说话框飞出的短句与轮廓像“若”的故事道具组成的学习插图中"
  },
  "划": {
    "src": "/illustrations/mnemonics/g5-u5212.svg",
    "label": "计划",
    "alt": "划字嵌在竖直刀刃与轮廓像“戈”的故事道具组成的学习插图中"
  },
  "典": {
    "src": "/illustrations/mnemonics/g5-u5178.svg",
    "label": "典礼",
    "alt": "典字嵌在轮廓像“八”的故事道具与轮廓像“曲”的故事道具组成的学习插图中"
  },
  "罪": {
    "src": "/illustrations/mnemonics/g5-u7f6a.svg",
    "label": "得罪",
    "alt": "罪字嵌在轮廓像“罒”的故事道具与轮廓像“非”的故事道具组成的学习插图中"
  },
  "廉": {
    "src": "/illustrations/mnemonics/g5-u5ec9.svg",
    "label": "廉颇",
    "alt": "廉字嵌在伸出长檐的屋舍与轮廓像“兼”的故事道具组成的学习插图中"
  },
  "抵": {
    "src": "/illustrations/mnemonics/g5-u62b5.svg",
    "label": "抵御",
    "alt": "抵字嵌在伸出并发力的手臂与轮廓像“氐”的故事道具组成的学习插图中"
  },
  "御": {
    "src": "/illustrations/mnemonics/g5-u5fa1.svg",
    "label": "抵御",
    "alt": "御字嵌在轮廓像“彳”的故事道具与轮廓像“卸”的故事道具组成的学习插图中"
  },
  "辞": {
    "src": "/illustrations/mnemonics/g5-u8f9e.svg",
    "label": "推辞",
    "alt": "辞字嵌在轮廓像“舌”的故事道具与轮廓像“辛”的故事道具组成的学习插图中"
  },
  "辱": {
    "src": "/illustrations/mnemonics/g5-u8fb1.svg",
    "label": "侮辱",
    "alt": "辱字嵌在轮廓像“辰”的故事道具与有刻度的手腕组成的学习插图中"
  },
  "擅": {
    "src": "/illustrations/mnemonics/g5-u64c5.svg",
    "label": "擅长",
    "alt": "擅字嵌在伸出并发力的手臂与轮廓像“亶”的故事道具组成的学习插图中"
  },
  "缶": {
    "src": "/illustrations/mnemonics/g5-u7f36.svg",
    "label": "击缶",
    "alt": "缶字嵌在轮廓像“午”的故事道具与高低相连的山峰组成的学习插图中"
  },
  "卿": {
    "src": "/illustrations/mnemonics/g5-u537f.svg",
    "label": "上卿",
    "alt": "卿字嵌在轮廓像“卩”的故事道具与轮廓像“卯”的故事道具组成的学习插图中"
  },
  "削": {
    "src": "/illustrations/mnemonics/g5-u524a.svg",
    "label": "削弱",
    "alt": "削字嵌在竖直刀刃与轮廓像“肖”的故事道具组成的学习插图中"
  },
  "袍": {
    "src": "/illustrations/mnemonics/g5-u888d.svg",
    "label": "战袍",
    "alt": "袍字嵌在展开衣襟的上衣与轮廓像“包”的故事道具组成的学习插图中"
  },
  "召": {
    "src": "/illustrations/mnemonics/g5-u53ec.svg",
    "label": "召集",
    "alt": "召字嵌在方形传声窗与弯柄刀具组成的学习插图中"
  },
  "议": {
    "src": "/illustrations/mnemonics/g5-u8bae.svg",
    "label": "商议",
    "alt": "议字嵌在从说话框飞出的短句与轮廓像“义”的故事道具组成的学习插图中"
  },
  "缺": {
    "src": "/illustrations/mnemonics/g5-u7f3a.svg",
    "label": "缺少",
    "alt": "缺字嵌在轮廓像“缶”的故事道具与轮廓像“夬”的故事道具组成的学习插图中"
  },
  "宫": {
    "src": "/illustrations/mnemonics/g5-u5bab.svg",
    "label": "王宫",
    "alt": "宫字嵌在安稳覆盖的屋顶与轮廓像“吕”的故事道具组成的学习插图中"
  },
  "献": {
    "src": "/illustrations/mnemonics/g5-u732e.svg",
    "label": "献上",
    "alt": "献字嵌在轮廓像“犬”的故事道具与轮廓像“南”的故事道具组成的学习插图中"
  },
  "承": {
    "src": "/illustrations/mnemonics/g5-u627f.svg",
    "label": "承诺",
    "alt": "承字嵌在张开的手掌与轮廓像“氶”的故事道具、轮廓像“三”的故事道具组成的学习插图中"
  },
  "抄": {
    "src": "/illustrations/mnemonics/g5-u6284.svg",
    "label": "抄写",
    "alt": "抄字嵌在伸出并发力的手臂与轮廓像“少”的故事道具组成的学习插图中"
  },
  "怯": {
    "src": "/illustrations/mnemonics/g5-u602f.svg",
    "label": "胆怯",
    "alt": "怯字嵌在跳动的心形灯带与轮廓像“去”的故事道具组成的学习插图中"
  },
  "拒": {
    "src": "/illustrations/mnemonics/g5-u62d2.svg",
    "label": "拒绝",
    "alt": "拒字嵌在伸出并发力的手臂与轮廓像“巨”的故事道具组成的学习插图中"
  },
  "荆": {
    "src": "/illustrations/mnemonics/g5-u8346.svg",
    "label": "荆条",
    "alt": "荆字嵌在竖直刀刃与成排草叶与花梗、轮廓像“刑”的故事道具组成的学习插图中"
  },
  "鸵": {
    "src": "/illustrations/mnemonics/g5-u9e35.svg",
    "label": "鸵鸟",
    "alt": "鸵字嵌在舒展翅尾的小鸟与轮廓像“它”的故事道具组成的学习插图中"
  },
  "赢": {
    "src": "/illustrations/mnemonics/g5-u8d62.svg",
    "label": "赢家",
    "alt": "赢字嵌在被托起的贝壳与轮廓像“𣎆”的故事道具组成的学习插图中"
  },
  "冠": {
    "src": "/illustrations/mnemonics/g5-u51a0.svg",
    "label": "冠军",
    "alt": "冠字嵌在轮廓像“冖”的故事道具与轮廓像“㝴”的故事道具组成的学习插图中"
  },
  "俯": {
    "src": "/illustrations/mnemonics/g5-u4fef.svg",
    "label": "俯冲",
    "alt": "俯字嵌在侧身站立的人与轮廓像“府”的故事道具组成的学习插图中"
  },
  "喷": {
    "src": "/illustrations/mnemonics/g5-u55b7.svg",
    "label": "喷气",
    "alt": "喷字嵌在方形传声窗与轮廓像“贲”的故事道具组成的学习插图中"
  },
  "枚": {
    "src": "/illustrations/mnemonics/g5-u679a.svg",
    "label": "一枚",
    "alt": "枚字嵌在有横枝、直干和斜根的大树与轮廓像“⺙”的故事道具组成的学习插图中"
  },
  "箭": {
    "src": "/illustrations/mnemonics/g5-u7bad.svg",
    "label": "弓箭",
    "alt": "箭字嵌在两簇竹叶与轮廓像“前”的故事道具组成的学习插图中"
  },
  "浩": {
    "src": "/illustrations/mnemonics/g5-u6d69.svg",
    "label": "浩大",
    "alt": "浩字嵌在三股清亮水流与轮廓像“告”的故事道具组成的学习插图中"
  },
  "筒": {
    "src": "/illustrations/mnemonics/g5-u7b52.svg",
    "label": "圆筒",
    "alt": "筒字嵌在两簇竹叶与轮廓像“同”的故事道具组成的学习插图中"
  },
  "束": {
    "src": "/illustrations/mnemonics/g5-u675f.svg",
    "label": "一束",
    "alt": "束字嵌在有横枝、直干和斜根的大树与方形传声窗组成的学习插图中"
  },
  "赤": {
    "src": "/illustrations/mnemonics/g5-u8d64.svg",
    "label": "赤道",
    "alt": "赤字嵌在分层的土台与完整物象组成的学习插图中"
  },
  "圈": {
    "src": "/illustrations/mnemonics/g5-u5708.svg",
    "label": "圆圈",
    "alt": "圈字嵌在轮廓像“囗”的故事道具与轮廓像“卷”的故事道具组成的学习插图中"
  },
  "置": {
    "src": "/illustrations/mnemonics/g5-u7f6e.svg",
    "label": "位置",
    "alt": "置字嵌在轮廓像“罒”的故事道具与轮廓像“直”的故事道具组成的学习插图中"
  },
  "侵": {
    "src": "/illustrations/mnemonics/g5-u4fb5.svg",
    "label": "侵略",
    "alt": "侵字嵌在侧身站立的人与完整物象组成的学习插图中"
  },
  "略": {
    "src": "/illustrations/mnemonics/g5-u7565.svg",
    "label": "侵略",
    "alt": "略字嵌在分成四格的田地与轮廓像“各”的故事道具组成的学习插图中"
  },
  "垒": {
    "src": "/illustrations/mnemonics/g5-u5792.svg",
    "label": "堡垒",
    "alt": "垒字嵌在分层的土台与轮廓像“厽”的故事道具组成的学习插图中"
  },
  "任": {
    "src": "/illustrations/mnemonics/g5-u4efb.svg",
    "label": "任丘",
    "alt": "任字嵌在侧身站立的人与轮廓像“壬”的故事道具组成的学习插图中"
  },
  "丘": {
    "src": "/illustrations/mnemonics/g5-u4e18.svg",
    "label": "任丘",
    "alt": "丘字嵌在轮廓像“一”的故事道具与轮廓像“斤”的故事道具组成的学习插图中"
  },
  "搁": {
    "src": "/illustrations/mnemonics/g5-u6401.svg",
    "label": "搁置",
    "alt": "搁字嵌在伸出并发力的手臂与轮廓像“阁”的故事道具组成的学习插图中"
  },
  "陷": {
    "src": "/illustrations/mnemonics/g5-u9677.svg",
    "label": "陷坑",
    "alt": "陷字嵌在高低相接的土坡与轮廓像“臽”的故事道具组成的学习插图中"
  },
  "拐": {
    "src": "/illustrations/mnemonics/g5-u62d0.svg",
    "label": "拐弯",
    "alt": "拐字嵌在伸出并发力的手臂与轮廓像“另”的故事道具组成的学习插图中"
  },
  "岔": {
    "src": "/illustrations/mnemonics/g5-u5c94.svg",
    "label": "岔道",
    "alt": "岔字嵌在高低相连的山峰与轮廓像“分”的故事道具组成的学习插图中"
  },
  "筑": {
    "src": "/illustrations/mnemonics/g5-u7b51.svg",
    "label": "修筑",
    "alt": "筑字嵌在两簇竹叶与轮廓像“巩”的故事道具组成的学习插图中"
  },
  "堡": {
    "src": "/illustrations/mnemonics/g5-u5821.svg",
    "label": "堡垒",
    "alt": "堡字嵌在分层的土台与轮廓像“保”的故事道具组成的学习插图中"
  },
  "党": {
    "src": "/illustrations/mnemonics/g5-u515a.svg",
    "label": "党员",
    "alt": "党字嵌在轮廓像“儿”的故事道具与轮廓像“龸”的故事道具、轮廓像“兄”的故事道具组成的学习插图中"
  },
  "妨": {
    "src": "/illustrations/mnemonics/g5-u59a8.svg",
    "label": "妨碍",
    "alt": "妨字嵌在照料幼苗的人影与轮廓像“方”的故事道具组成的学习插图中"
  },
  "蔽": {
    "src": "/illustrations/mnemonics/g5-u853d.svg",
    "label": "隐蔽",
    "alt": "蔽字嵌在成排草叶与花梗与轮廓像“敝”的故事道具组成的学习插图中"
  },
  "酬": {
    "src": "/illustrations/mnemonics/g5-u916c.svg",
    "label": "酬谢",
    "alt": "酬字嵌在封口酒坛与轮廓像“州”的故事道具组成的学习插图中"
  },
  "誓": {
    "src": "/illustrations/mnemonics/g5-u8a93.svg",
    "label": "发誓",
    "alt": "誓字嵌在从口中升起的言语与轮廓像“折”的故事道具组成的学习插图中"
  },
  "谎": {
    "src": "/illustrations/mnemonics/g5-u8c0e.svg",
    "label": "谎话",
    "alt": "谎字嵌在从说话框飞出的短句与轮廓像“荒”的故事道具组成的学习插图中"
  },
  "牺": {
    "src": "/illustrations/mnemonics/g5-u727a.svg",
    "label": "牺牲",
    "alt": "牺字嵌在带角的牛头与轮廓像“西”的故事道具组成的学习插图中"
  },
  "珍": {
    "src": "/illustrations/mnemonics/g5-u73cd.svg",
    "label": "珍宝",
    "alt": "珍字嵌在三层玉架与轮廓像“㐱”的故事道具组成的学习插图中"
  },
  "叮": {
    "src": "/illustrations/mnemonics/g5-u53ee.svg",
    "label": "叮嘱",
    "alt": "叮字嵌在方形传声窗与轮廓像“丁”的故事道具组成的学习插图中"
  },
  "嘱": {
    "src": "/illustrations/mnemonics/g5-u5631.svg",
    "label": "叮嘱",
    "alt": "嘱字嵌在方形传声窗与轮廓像“属”的故事道具组成的学习插图中"
  },
  "塌": {
    "src": "/illustrations/mnemonics/g5-u584c.svg",
    "label": "倒塌",
    "alt": "塌字嵌在分层的土台与轮廓像“𦐇”的故事道具组成的学习插图中"
  },
  "焦": {
    "src": "/illustrations/mnemonics/g5-u7126.svg",
    "label": "焦急",
    "alt": "焦字嵌在四点温暖火光与轮廓像“隹”的故事道具组成的学习插图中"
  },
  "延": {
    "src": "/illustrations/mnemonics/g5-u5ef6.svg",
    "label": "延迟",
    "alt": "延字嵌在轮廓像“廴”的故事道具与完整物象组成的学习插图中"
  },
  "灾": {
    "src": "/illustrations/mnemonics/g5-u707e.svg",
    "label": "灾难",
    "alt": "灾字嵌在向上跳动的火焰与安稳覆盖的屋顶组成的学习插图中"
  },
  "悔": {
    "src": "/illustrations/mnemonics/g5-u6094.svg",
    "label": "后悔",
    "alt": "悔字嵌在跳动的心形灯带与轮廓像“每”的故事道具组成的学习插图中"
  },
  "扶": {
    "src": "/illustrations/mnemonics/g5-u6276.svg",
    "label": "扶持",
    "alt": "扶字嵌在伸出并发力的手臂与轮廓像“夫”的故事道具组成的学习插图中"
  },
  "嫂": {
    "src": "/illustrations/mnemonics/g5-u5ac2.svg",
    "label": "嫂子",
    "alt": "嫂字嵌在照料幼苗的人影与轮廓像“叟”的故事道具组成的学习插图中"
  },
  "恳": {
    "src": "/illustrations/mnemonics/g5-u6073.svg",
    "label": "恳求",
    "alt": "恳字嵌在心形灯带与三点微光与轮廓像“艮”的故事道具组成的学习插图中"
  },
  "筛": {
    "src": "/illustrations/mnemonics/g5-u7b5b.svg",
    "label": "筛子",
    "alt": "筛字嵌在两簇竹叶与轮廓像“师”的故事道具组成的学习插图中"
  },
  "歹": {
    "src": "/illustrations/mnemonics/g5-u6b79.svg",
    "label": "歹人",
    "alt": "歹字嵌在轮廓像“一”的故事道具与轮廓像“夕”的故事道具组成的学习插图中"
  },
  "罕": {
    "src": "/illustrations/mnemonics/g5-u7f55.svg",
    "label": "稀罕",
    "alt": "罕字嵌在轮廓像“⺳”的故事道具与轮廓像“干”的故事道具组成的学习插图中"
  },
  "梭": {
    "src": "/illustrations/mnemonics/g5-u68ad.svg",
    "label": "梭子",
    "alt": "梭字嵌在有横枝、直干和斜根的大树与轮廓像“夋”的故事道具组成的学习插图中"
  },
  "监": {
    "src": "/illustrations/mnemonics/g5-u76d1.svg",
    "label": "监狱",
    "alt": "监字嵌在浅口器皿与完整物象组成的学习插图中"
  },
  "狱": {
    "src": "/illustrations/mnemonics/g5-u72f1.svg",
    "label": "监狱",
    "alt": "狱字嵌在奔跑动物的侧影与完整物象组成的学习插图中"
  },
  "酿": {
    "src": "/illustrations/mnemonics/g5-u917f.svg",
    "label": "酿酒",
    "alt": "酿字嵌在封口酒坛与轮廓像“良”的故事道具组成的学习插图中"
  },
  "瞌": {
    "src": "/illustrations/mnemonics/g5-u778c.svg",
    "label": "瞌睡",
    "alt": "瞌字嵌在方框中的眼睛与轮廓像“盍”的故事道具组成的学习插图中"
  },
  "落": {
    "src": "/illustrations/mnemonics/g5-u843d.svg",
    "label": "落在后边",
    "alt": "落字嵌在成排草叶与花梗与轮廓像“洛”的故事道具组成的学习插图中"
  },
  "婚": {
    "src": "/illustrations/mnemonics/g5-u5a5a.svg",
    "label": "结婚",
    "alt": "婚字嵌在照料幼苗的人影与轮廓像“昏”的故事道具组成的学习插图中"
  },
  "郎": {
    "src": "/illustrations/mnemonics/g5-u90ce.svg",
    "label": "牛郎",
    "alt": "郎字嵌在高低相接的土坡与完整物象组成的学习插图中"
  },
  "爹": {
    "src": "/illustrations/mnemonics/g5-u7239.svg",
    "label": "爹娘",
    "alt": "爹字嵌在轮廓像“父”的故事道具与轮廓像“多”的故事道具组成的学习插图中"
  },
  "辆": {
    "src": "/illustrations/mnemonics/g5-u8f86.svg",
    "label": "车辆",
    "alt": "辆字嵌在有轮轴的车架与轮廓像“两”的故事道具组成的学习插图中"
  },
  "纱": {
    "src": "/illustrations/mnemonics/g5-u7eb1.svg",
    "label": "纱衣",
    "alt": "纱字嵌在盘绕的细丝线与轮廓像“少”的故事道具组成的学习插图中"
  },
  "妻": {
    "src": "/illustrations/mnemonics/g5-u59bb.svg",
    "label": "妻子",
    "alt": "妻字嵌在照料幼苗的人影与完整物象组成的学习插图中"
  },
  "趟": {
    "src": "/illustrations/mnemonics/g5-u8d9f.svg",
    "label": "一趟",
    "alt": "趟字嵌在向前迈出的脚步与轮廓像“尚”的故事道具组成的学习插图中"
  },
  "托": {
    "src": "/illustrations/mnemonics/g5-u6258.svg",
    "label": "托付",
    "alt": "托字嵌在伸出并发力的手臂与轮廓像“乇”的故事道具组成的学习插图中"
  },
  "溜": {
    "src": "/illustrations/mnemonics/g5-u6e9c.svg",
    "label": "溜走",
    "alt": "溜字嵌在三股清亮水流与轮廓像“留”的故事道具组成的学习插图中"
  },
  "辈": {
    "src": "/illustrations/mnemonics/g5-u8f88.svg",
    "label": "长辈",
    "alt": "辈字嵌在轮廓像“非”的故事道具与有轮轴的车架组成的学习插图中"
  },
  "挨": {
    "src": "/illustrations/mnemonics/g5-u6328.svg",
    "label": "挨打",
    "alt": "挨字嵌在伸出并发力的手臂与轮廓像“矣”的故事道具组成的学习插图中"
  },
  "俭": {
    "src": "/illustrations/mnemonics/g5-u4fed.svg",
    "label": "节俭",
    "alt": "俭字嵌在侧身站立的人与轮廓像“佥”的故事道具组成的学习插图中"
  },
  "皇": {
    "src": "/illustrations/mnemonics/g5-u7687.svg",
    "label": "皇帝",
    "alt": "皇字嵌在明亮的小窗与三层玉架组成的学习插图中"
  },
  "偎": {
    "src": "/illustrations/mnemonics/g5-u504e.svg",
    "label": "依偎",
    "alt": "偎字嵌在侧身站立的人与轮廓像“畏”的故事道具组成的学习插图中"
  },
  "衰": {
    "src": "/illustrations/mnemonics/g5-u8870.svg",
    "label": "衰老",
    "alt": "衰字嵌在展开衣襟的上衣与完整物象组成的学习插图中"
  },
  "珊": {
    "src": "/illustrations/mnemonics/g5-u73ca.svg",
    "label": "珊瑚",
    "alt": "珊字嵌在三层玉架与轮廓像“册”的故事道具组成的学习插图中"
  },
  "瑚": {
    "src": "/illustrations/mnemonics/g5-u745a.svg",
    "label": "珊瑚",
    "alt": "瑚字嵌在三层玉架与轮廓像“胡”的故事道具组成的学习插图中"
  },
  "礁": {
    "src": "/illustrations/mnemonics/g5-u7901.svg",
    "label": "暗礁",
    "alt": "礁字嵌在带切面的岩石与轮廓像“焦”的故事道具组成的学习插图中"
  },
  "筐": {
    "src": "/illustrations/mnemonics/g5-u7b50.svg",
    "label": "竹筐",
    "alt": "筐字嵌在两簇竹叶与轮廓像“匡”的故事道具组成的学习插图中"
  },
  "拗": {
    "src": "/illustrations/mnemonics/g5-u62d7.svg",
    "label": "执拗",
    "alt": "拗字嵌在伸出并发力的手臂与轮廓像“幼”的故事道具组成的学习插图中"
  },
  "乃": {
    "src": "/illustrations/mnemonics/g5-u4e43.svg",
    "label": "乃至",
    "alt": "乃字嵌在轮廓像“丿”的故事道具与轮廓像“㇎”的故事道具组成的学习插图中"
  },
  "熏": {
    "src": "/illustrations/mnemonics/g5-u718f.svg",
    "label": "熏陶",
    "alt": "熏字嵌在四点温暖火光与完整物象组成的学习插图中"
  },
  "亥": {
    "src": "/illustrations/mnemonics/g5-u4ea5.svg",
    "label": "亥时",
    "alt": "亥字嵌在轮廓像“亠”的故事道具与展开双臂的人组成的学习插图中"
  },
  "恃": {
    "src": "/illustrations/mnemonics/g5-u6043.svg",
    "label": "恃强",
    "alt": "恃字嵌在跳动的心形灯带与轮廓像“寺”的故事道具组成的学习插图中"
  },
  "擞": {
    "src": "/illustrations/mnemonics/g5-u64de.svg",
    "label": "抖擞",
    "alt": "擞字嵌在伸出并发力的手臂与轮廓像“数”的故事道具组成的学习插图中"
  },
  "祭": {
    "src": "/illustrations/mnemonics/g5-u796d.svg",
    "label": "祭祀",
    "alt": "祭字嵌在轮廓像“示”的故事道具与完整物象组成的学习插图中"
  },
  "哀": {
    "src": "/illustrations/mnemonics/g5-u54c0.svg",
    "label": "哀伤",
    "alt": "哀字嵌在方形传声窗与展开衣襟的上衣组成的学习插图中"
  },
  "拘": {
    "src": "/illustrations/mnemonics/g5-u62d8.svg",
    "label": "拘束",
    "alt": "拘字嵌在伸出并发力的手臂与轮廓像“句”的故事道具组成的学习插图中"
  },
  "泻": {
    "src": "/illustrations/mnemonics/g5-u6cfb.svg",
    "label": "倾泻",
    "alt": "泻字嵌在三股清亮水流与轮廓像“写”的故事道具组成的学习插图中"
  },
  "鳞": {
    "src": "/illustrations/mnemonics/g5-u9cde.svg",
    "label": "鱼鳞",
    "alt": "鳞字嵌在有鳍和尾巴的鱼与轮廓像“粦”的故事道具组成的学习插图中"
  },
  "惶": {
    "src": "/illustrations/mnemonics/g5-u60f6.svg",
    "label": "惶恐",
    "alt": "惶字嵌在跳动的心形灯带与轮廓像“皇”的故事道具组成的学习插图中"
  },
  "胎": {
    "src": "/illustrations/mnemonics/g5-u80ce.svg",
    "label": "胎儿",
    "alt": "胎字嵌在轮廓像“⺼”的故事道具与弯月形灯盘、轮廓像“台”的故事道具组成的学习插图中"
  },
  "履": {
    "src": "/illustrations/mnemonics/g5-u5c65.svg",
    "label": "履行",
    "alt": "履字嵌在轮廓像“尸”的故事道具与轮廓像“復”的故事道具组成的学习插图中"
  },
  "哉": {
    "src": "/illustrations/mnemonics/g5-u54c9.svg",
    "label": "美哉",
    "alt": "哉字嵌在方形传声窗与轮廓像“𢦏”的故事道具组成的学习插图中"
  },
  "潜": {
    "src": "/illustrations/mnemonics/g5-u6f5c.svg",
    "label": "潜水",
    "alt": "潜字嵌在三股清亮水流与轮廓像“替”的故事道具组成的学习插图中"
  },
  "试": {
    "src": "/illustrations/mnemonics/g5-u8bd5.svg",
    "label": "考试",
    "alt": "试字嵌在从说话框飞出的短句与轮廓像“式”的故事道具组成的学习插图中"
  },
  "纵": {
    "src": "/illustrations/mnemonics/g5-u7eb5.svg",
    "label": "纵横",
    "alt": "纵字嵌在盘绕的细丝线与轮廓像“从”的故事道具组成的学习插图中"
  },
  "疆": {
    "src": "/illustrations/mnemonics/g5-u7586.svg",
    "label": "边疆",
    "alt": "疆字嵌在分成四格的田地与轮廓像“畺”的故事道具组成的学习插图中"
  },
  "估": {
    "src": "/illustrations/mnemonics/g5-u4f30.svg",
    "label": "估计",
    "alt": "估字嵌在侧身站立的人与轮廓像“古”的故事道具组成的学习插图中"
  },
  "煌": {
    "src": "/illustrations/mnemonics/g5-u714c.svg",
    "label": "辉煌",
    "alt": "煌字嵌在向上跳动的火焰与轮廓像“皇”的故事道具组成的学习插图中"
  },
  "珑": {
    "src": "/illustrations/mnemonics/g5-u73d1.svg",
    "label": "玲珑",
    "alt": "珑字嵌在三层玉架与轮廓像“龙”的故事道具组成的学习插图中"
  },
  "剔": {
    "src": "/illustrations/mnemonics/g5-u5254.svg",
    "label": "剔透",
    "alt": "剔字嵌在竖直刀刃与轮廓像“易”的故事道具组成的学习插图中"
  },
  "澜": {
    "src": "/illustrations/mnemonics/g5-u6f9c.svg",
    "label": "波澜",
    "alt": "澜字嵌在三股清亮水流与轮廓像“阑”的故事道具组成的学习插图中"
  },
  "瑶": {
    "src": "/illustrations/mnemonics/g5-u7476.svg",
    "label": "瑶台",
    "alt": "瑶字嵌在三层玉架与完整物象组成的学习插图中"
  },
  "陵": {
    "src": "/illustrations/mnemonics/g5-u9675.svg",
    "label": "陵园",
    "alt": "陵字嵌在高低相接的土坡与轮廓像“夌”的故事道具组成的学习插图中"
  },
  "宏": {
    "src": "/illustrations/mnemonics/g5-u5b8f.svg",
    "label": "宏伟",
    "alt": "宏字嵌在安稳覆盖的屋顶与轮廓像“厷”的故事道具组成的学习插图中"
  },
  "奉": {
    "src": "/illustrations/mnemonics/g5-u5949.svg",
    "label": "奉命",
    "alt": "奉字嵌在正面伸展的人与轮廓像“𡗗”的故事道具组成的学习插图中"
  },
  "烬": {
    "src": "/illustrations/mnemonics/g5-u70ec.svg",
    "label": "灰烬",
    "alt": "烬字嵌在向上跳动的火焰与轮廓像“尽”的故事道具组成的学习插图中"
  },
  "毁": {
    "src": "/illustrations/mnemonics/g5-u6bc1.svg",
    "label": "毁灭",
    "alt": "毁字嵌在轮廓像“殳”的故事道具与完整物象组成的学习插图中"
  },
  "损": {
    "src": "/illustrations/mnemonics/g5-u635f.svg",
    "label": "损失",
    "alt": "损字嵌在伸出并发力的手臂与轮廓像“员”的故事道具组成的学习插图中"
  },
  "拱": {
    "src": "/illustrations/mnemonics/g5-u62f1.svg",
    "label": "拱桥",
    "alt": "拱字嵌在伸出并发力的手臂与轮廓像“共”的故事道具组成的学习插图中"
  },
  "辉": {
    "src": "/illustrations/mnemonics/g5-u8f89.svg",
    "label": "辉煌",
    "alt": "辉字嵌在轮廓像“⺌”的故事道具与轮廓像“光”的故事道具、轮廓像“军”的故事道具组成的学习插图中"
  },
  "殿": {
    "src": "/illustrations/mnemonics/g5-u6bbf.svg",
    "label": "宫殿",
    "alt": "殿字嵌在轮廓像“殳”的故事道具与轮廓像“𡱒”的故事道具组成的学习插图中"
  },
  "览": {
    "src": "/illustrations/mnemonics/g5-u89c8.svg",
    "label": "游览",
    "alt": "览字嵌在轮廓像“见”的故事道具与完整物象组成的学习插图中"
  },
  "境": {
    "src": "/illustrations/mnemonics/g5-u5883.svg",
    "label": "环境",
    "alt": "境字嵌在分层的土台与轮廓像“竟”的故事道具组成的学习插图中"
  },
  "唐": {
    "src": "/illustrations/mnemonics/g5-u5510.svg",
    "label": "唐代",
    "alt": "唐字嵌在方形传声窗与伸出长檐的屋舍组成的学习插图中"
  },
  "闯": {
    "src": "/illustrations/mnemonics/g5-u95ef.svg",
    "label": "闯入",
    "alt": "闯字嵌在打开的双扇门与奔跑的马与鬃尾组成的学习插图中"
  },
  "销": {
    "src": "/illustrations/mnemonics/g5-u9500.svg",
    "label": "销毁",
    "alt": "销字嵌在金属工具架与轮廓像“肖”的故事道具组成的学习插图中"
  },
  "瞒": {
    "src": "/illustrations/mnemonics/g5-u7792.svg",
    "label": "隐瞒",
    "alt": "瞒字嵌在方框中的眼睛与完整物象组成的学习插图中"
  },
  "域": {
    "src": "/illustrations/mnemonics/g5-u57df.svg",
    "label": "海域",
    "alt": "域字嵌在分层的土台与轮廓像“或”的故事道具组成的学习插图中"
  },
  "艇": {
    "src": "/illustrations/mnemonics/g5-u8247.svg",
    "label": "小艇",
    "alt": "艇字嵌在细长的小船与轮廓像“廷”的故事道具组成的学习插图中"
  },
  "矛": {
    "src": "/illustrations/mnemonics/g5-u77db.svg",
    "label": "矛盾",
    "alt": "矛字嵌在轮廓像“龴”的故事道具与完整物象组成的学习插图中"
  },
  "盾": {
    "src": "/illustrations/mnemonics/g5-u76fe.svg",
    "label": "矛盾",
    "alt": "盾字嵌在方框中的眼睛与轮廓像“⺁”的故事道具、轮廓像“𥃭”的故事道具组成的学习插图中"
  },
  "筷": {
    "src": "/illustrations/mnemonics/g5-u7b77.svg",
    "label": "筷子",
    "alt": "筷字嵌在两簇竹叶与轮廓像“快”的故事道具组成的学习插图中"
  },
  "炊": {
    "src": "/illustrations/mnemonics/g5-u708a.svg",
    "label": "炊烟",
    "alt": "炊字嵌在向上跳动的火焰与张口舒气的人影组成的学习插图中"
  },
  "哼": {
    "src": "/illustrations/mnemonics/g5-u54fc.svg",
    "label": "哼",
    "alt": "哼字嵌在方形传声窗与轮廓像“亨”的故事道具组成的学习插图中"
  },
  "喉": {
    "src": "/illustrations/mnemonics/g5-u5589.svg",
    "label": "喉咙",
    "alt": "喉字嵌在方形传声窗与轮廓像“侯”的故事道具组成的学习插图中"
  },
  "咙": {
    "src": "/illustrations/mnemonics/g5-u5499.svg",
    "label": "喉咙",
    "alt": "咙字嵌在方形传声窗与轮廓像“龙”的故事道具组成的学习插图中"
  },
  "哽": {
    "src": "/illustrations/mnemonics/g5-u54fd.svg",
    "label": "哽咽",
    "alt": "哽字嵌在方形传声窗与轮廓像“更”的故事道具组成的学习插图中"
  },
  "勺": {
    "src": "/illustrations/mnemonics/g5-u52fa.svg",
    "label": "勺子",
    "alt": "勺字嵌在轮廓像“勹”的故事道具与轮廓像“丶”的故事道具组成的学习插图中"
  },
  "搅": {
    "src": "/illustrations/mnemonics/g5-u6405.svg",
    "label": "搅拌",
    "alt": "搅字嵌在伸出并发力的手臂与轮廓像“觉”的故事道具组成的学习插图中"
  },
  "舀": {
    "src": "/illustrations/mnemonics/g5-u8200.svg",
    "label": "舀水",
    "alt": "舀字嵌在轮廓像“臼”的故事道具与轮廓像“爫”的故事道具组成的学习插图中"
  },
  "摄": {
    "src": "/illustrations/mnemonics/g5-u6444.svg",
    "label": "摄氏",
    "alt": "摄字嵌在伸出并发力的手臂与轮廓像“聂”的故事道具组成的学习插图中"
  },
  "殖": {
    "src": "/illustrations/mnemonics/g5-u6b96.svg",
    "label": "繁殖",
    "alt": "殖字嵌在轮廓像“歹”的故事道具与轮廓像“直”的故事道具组成的学习插图中"
  },
  "炭": {
    "src": "/illustrations/mnemonics/g5-u70ad.svg",
    "label": "煤炭",
    "alt": "炭字嵌在向上跳动的火焰与高低相连的山峰、轮廓像“灰”的故事道具组成的学习插图中"
  },
  "疗": {
    "src": "/illustrations/mnemonics/g5-u7597.svg",
    "label": "治疗",
    "alt": "疗字嵌在轮廓像“疒”的故事道具与轮廓像“了”的故事道具组成的学习插图中"
  },
  "氏": {
    "src": "/illustrations/mnemonics/g5-u6c0f.svg",
    "label": "摄氏",
    "alt": "氏字嵌在轮廓像“氏”的故事道具与完整物象组成的学习插图中"
  },
  "粮": {
    "src": "/illustrations/mnemonics/g5-u7cae.svg",
    "label": "粮食",
    "alt": "粮字嵌在米架和四散米粒与轮廓像“良”的故事道具组成的学习插图中"
  },
  "区": {
    "src": "/illustrations/mnemonics/g5-u533a.svg",
    "label": "地区",
    "alt": "区字嵌在轮廓像“匸”的故事道具与轮廓像“匚”的故事道具、轮廓像“乂”的故事道具组成的学习插图中"
  },
  "杀": {
    "src": "/illustrations/mnemonics/g5-u6740.svg",
    "label": "杀菌",
    "alt": "杀字嵌在有横枝、直干和斜根的大树与轮廓像“乂”的故事道具、轮廓像“朩”的故事道具组成的学习插图中"
  },
  "菌": {
    "src": "/illustrations/mnemonics/g5-u83cc.svg",
    "label": "杀菌",
    "alt": "菌字嵌在成排草叶与花梗与轮廓像“囷”的故事道具组成的学习插图中"
  },
  "驯": {
    "src": "/illustrations/mnemonics/g5-u9a6f.svg",
    "label": "驯良",
    "alt": "驯字嵌在奔跑的马与鬃尾与轮廓像“川”的故事道具组成的学习插图中"
  },
  "矫": {
    "src": "/illustrations/mnemonics/g5-u77eb.svg",
    "label": "矫健",
    "alt": "矫字嵌在轮廓像“矢”的故事道具与轮廓像“乔”的故事道具组成的学习插图中"
  },
  "歇": {
    "src": "/illustrations/mnemonics/g5-u6b47.svg",
    "label": "歇息",
    "alt": "歇字嵌在张口舒气的人影与轮廓像“曷”的故事道具组成的学习插图中"
  },
  "杈": {
    "src": "/illustrations/mnemonics/g5-u6748.svg",
    "label": "树杈",
    "alt": "杈字嵌在有横枝、直干和斜根的大树与轮廓像“叉”的故事道具组成的学习插图中"
  },
  "藓": {
    "src": "/illustrations/mnemonics/g5-u85d3.svg",
    "label": "苔藓",
    "alt": "藓字嵌在成排草叶与花梗与轮廓像“鲜”的故事道具组成的学习插图中"
  },
  "狭": {
    "src": "/illustrations/mnemonics/g5-u72ed.svg",
    "label": "狭窄",
    "alt": "狭字嵌在奔跑动物的侧影与轮廓像“夹”的故事道具组成的学习插图中"
  },
  "勉": {
    "src": "/illustrations/mnemonics/g5-u52c9.svg",
    "label": "勉强",
    "alt": "勉字嵌在弯曲而发力的手臂与轮廓像“免”的故事道具组成的学习插图中"
  },
  "锥": {
    "src": "/illustrations/mnemonics/g5-u9525.svg",
    "label": "圆锥",
    "alt": "锥字嵌在金属工具架与轮廓像“隹”的故事道具组成的学习插图中"
  },
  "鼠": {
    "src": "/illustrations/mnemonics/g5-u9f20.svg",
    "label": "松鼠",
    "alt": "鼠字嵌在轮廓像“臼”的故事道具与完整物象组成的学习插图中"
  },
  "秀": {
    "src": "/illustrations/mnemonics/g5-u79c0.svg",
    "label": "清秀",
    "alt": "秀字嵌在低垂的谷穗与轮廓像“乃”的故事道具组成的学习插图中"
  },
  "玲": {
    "src": "/illustrations/mnemonics/g5-u73b2.svg",
    "label": "玲珑",
    "alt": "玲字嵌在三层玉架与轮廓像“令”的故事道具组成的学习插图中"
  },
  "帽": {
    "src": "/illustrations/mnemonics/g5-u5e3d.svg",
    "label": "帽子",
    "alt": "帽字嵌在垂下的布幅与轮廓像“冒”的故事道具组成的学习插图中"
  },
  "尾": {
    "src": "/illustrations/mnemonics/g5-u5c3e.svg",
    "label": "尾巴",
    "alt": "尾字嵌在轮廓像“尸”的故事道具与轮廓像“毛”的故事道具组成的学习插图中"
  },
  "窝": {
    "src": "/illustrations/mnemonics/g5-u7a9d.svg",
    "label": "鸟窝",
    "alt": "窝字嵌在带采光孔的洞顶与轮廓像“呙”的故事道具组成的学习插图中"
  },
  "滑": {
    "src": "/illustrations/mnemonics/g5-u6ed1.svg",
    "label": "光滑",
    "alt": "滑字嵌在三股清亮水流与轮廓像“骨”的故事道具组成的学习插图中"
  },
  "拾": {
    "src": "/illustrations/mnemonics/g5-u62fe.svg",
    "label": "拾取",
    "alt": "拾字嵌在伸出并发力的手臂与轮廓像“合”的故事道具组成的学习插图中"
  },
  "梳": {
    "src": "/illustrations/mnemonics/g5-u68b3.svg",
    "label": "梳理",
    "alt": "梳字嵌在有横枝、直干和斜根的大树与轮廓像“㐬”的故事道具组成的学习插图中"
  },
  "魄": {
    "src": "/illustrations/mnemonics/g5-u9b44.svg",
    "label": "魂魄",
    "alt": "魄字嵌在轮廓像“鬼”的故事道具与明亮的小窗组成的学习插图中"
  },
  "抑": {
    "src": "/illustrations/mnemonics/g5-u6291.svg",
    "label": "压抑",
    "alt": "抑字嵌在伸出并发力的手臂与轮廓像“卬”的故事道具组成的学习插图中"
  },
  "颓": {
    "src": "/illustrations/mnemonics/g5-u9893.svg",
    "label": "颓败",
    "alt": "颓字嵌在突出头部的人影与轮廓像“秃”的故事道具组成的学习插图中"
  },
  "纫": {
    "src": "/illustrations/mnemonics/g5-u7eab.svg",
    "label": "缝纫",
    "alt": "纫字嵌在盘绕的细丝线与轮廓像“刃”的故事道具组成的学习插图中"
  },
  "噪": {
    "src": "/illustrations/mnemonics/g5-u566a.svg",
    "label": "噪声",
    "alt": "噪字嵌在方形传声窗与轮廓像“喿”的故事道具组成的学习插图中"
  },
  "褐": {
    "src": "/illustrations/mnemonics/g5-u8910.svg",
    "label": "褐色",
    "alt": "褐字嵌在展开衣襟的上衣与轮廓像“曷”的故事道具组成的学习插图中"
  },
  "惫": {
    "src": "/illustrations/mnemonics/g5-u60eb.svg",
    "label": "疲惫",
    "alt": "惫字嵌在轮廓像“夂”的故事道具与轮廓像“思”的故事道具组成的学习插图中"
  },
  "耽": {
    "src": "/illustrations/mnemonics/g5-u803d.svg",
    "label": "耽误",
    "alt": "耽字嵌在竖起的耳朵与轮廓像“冘”的故事道具组成的学习插图中"
  },
  "兜": {
    "src": "/illustrations/mnemonics/g5-u515c.svg",
    "label": "衣兜",
    "alt": "兜字嵌在轮廓像“儿”的故事道具与完整物象组成的学习插图中"
  },
  "权": {
    "src": "/illustrations/mnemonics/g5-u6743.svg",
    "label": "权利",
    "alt": "权字嵌在有横枝、直干和斜根的大树与回转的右手组成的学习插图中"
  },
  "碌": {
    "src": "/illustrations/mnemonics/g5-u788c.svg",
    "label": "忙碌",
    "alt": "碌字嵌在带切面的岩石与轮廓像“录”的故事道具组成的学习插图中"
  },
  "吊": {
    "src": "/illustrations/mnemonics/g5-u540a.svg",
    "label": "吊起",
    "alt": "吊字嵌在方形传声窗与垂下的布幅组成的学习插图中"
  },
  "酷": {
    "src": "/illustrations/mnemonics/g5-u9177.svg",
    "label": "酷暑",
    "alt": "酷字嵌在封口酒坛与轮廓像“告”的故事道具组成的学习插图中"
  },
  "暑": {
    "src": "/illustrations/mnemonics/g5-u6691.svg",
    "label": "酷暑",
    "alt": "暑字嵌在有中央光带的日轮与轮廓像“者”的故事道具组成的学习插图中"
  },
  "脊": {
    "src": "/illustrations/mnemonics/g5-u810a.svg",
    "label": "脊背",
    "alt": "脊字嵌在轮廓像“⺼”的故事道具与弯月形灯盘组成的学习插图中"
  },
  "罩": {
    "src": "/illustrations/mnemonics/g5-u7f69.svg",
    "label": "笼罩",
    "alt": "罩字嵌在轮廓像“罒”的故事道具与轮廓像“卓”的故事道具组成的学习插图中"
  },
  "竟": {
    "src": "/illustrations/mnemonics/g5-u7adf.svg",
    "label": "竟然",
    "alt": "竟字嵌在轮廓像“立”的故事道具与轮廓像“音”的故事道具、轮廓像“儿”的故事道具组成的学习插图中"
  },
  "哇": {
    "src": "/illustrations/mnemonics/g5-u54c7.svg",
    "label": "好哇",
    "alt": "哇字嵌在方形传声窗与轮廓像“圭”的故事道具组成的学习插图中"
  },
  "忍": {
    "src": "/illustrations/mnemonics/g5-u5fcd.svg",
    "label": "忍受",
    "alt": "忍字嵌在心形灯带与三点微光与轮廓像“刃”的故事道具组成的学习插图中"
  },
  "械": {
    "src": "/illustrations/mnemonics/g5-u68b0.svg",
    "label": "机械",
    "alt": "械字嵌在有横枝、直干和斜根的大树与轮廓像“戒”的故事道具组成的学习插图中"
  },
  "酸": {
    "src": "/illustrations/mnemonics/g5-u9178.svg",
    "label": "心酸",
    "alt": "酸字嵌在封口酒坛与轮廓像“夋”的故事道具组成的学习插图中"
  },
  "茧": {
    "src": "/illustrations/mnemonics/g5-u8327.svg",
    "label": "蚕茧",
    "alt": "茧字嵌在成排草叶与花梗与弯身的小虫组成的学习插图中"
  },
  "栈": {
    "src": "/illustrations/mnemonics/g5-u6808.svg",
    "label": "客栈",
    "alt": "栈字嵌在有横枝、直干和斜根的大树与轮廓像“戋”的故事道具组成的学习插图中"
  },
  "冤": {
    "src": "/illustrations/mnemonics/g5-u51a4.svg",
    "label": "冤枉",
    "alt": "冤字嵌在轮廓像“冖”的故事道具与轮廓像“兔”的故事道具组成的学习插图中"
  },
  "枉": {
    "src": "/illustrations/mnemonics/g5-u6789.svg",
    "label": "冤枉",
    "alt": "枉字嵌在有横枝、直干和斜根的大树与三层玉架组成的学习插图中"
  },
  "恍": {
    "src": "/illustrations/mnemonics/g5-u604d.svg",
    "label": "恍惚",
    "alt": "恍字嵌在跳动的心形灯带与轮廓像“光”的故事道具组成的学习插图中"
  },
  "惚": {
    "src": "/illustrations/mnemonics/g5-u60da.svg",
    "label": "恍惚",
    "alt": "惚字嵌在跳动的心形灯带与轮廓像“忽”的故事道具组成的学习插图中"
  },
  "跷": {
    "src": "/illustrations/mnemonics/g5-u8df7.svg",
    "label": "跷跷板",
    "alt": "跷字嵌在脚印和落脚台与脚印和落脚台、轮廓像“尧”的故事道具组成的学习插图中"
  },
  "僻": {
    "src": "/illustrations/mnemonics/g5-u50fb.svg",
    "label": "偏僻",
    "alt": "僻字嵌在侧身站立的人与轮廓像“辟”的故事道具组成的学习插图中"
  },
  "委": {
    "src": "/illustrations/mnemonics/g5-u59d4.svg",
    "label": "委屈",
    "alt": "委字嵌在照料幼苗的人影与低垂的谷穗组成的学习插图中"
  },
  "迪": {
    "src": "/illustrations/mnemonics/g5-u8fea.svg",
    "label": "启迪",
    "alt": "迪字嵌在回转向前的小路与轮廓像“由”的故事道具组成的学习插图中"
  },
  "嫁": {
    "src": "/illustrations/mnemonics/g5-u5ac1.svg",
    "label": "出嫁",
    "alt": "嫁字嵌在照料幼苗的人影与轮廓像“家”的故事道具组成的学习插图中"
  },
  "缴": {
    "src": "/illustrations/mnemonics/g5-u7f34.svg",
    "label": "缴费",
    "alt": "缴字嵌在盘绕的细丝线与轮廓像“敫”的故事道具组成的学习插图中"
  },
  "榜": {
    "src": "/illustrations/mnemonics/g5-u699c.svg",
    "label": "榜样",
    "alt": "榜字嵌在有横枝、直干和斜根的大树与轮廓像“旁”的故事道具组成的学习插图中"
  },
  "兼": {
    "src": "/illustrations/mnemonics/g5-u517c.svg",
    "label": "兼职",
    "alt": "兼字嵌在轮廓像“丷”的故事道具与轮廓像“䒑”的故事道具组成的学习插图中"
  },
  "嘲": {
    "src": "/illustrations/mnemonics/g5-u5632.svg",
    "label": "嘲笑",
    "alt": "嘲字嵌在方形传声窗与轮廓像“朝”的故事道具组成的学习插图中"
  },
  "枕": {
    "src": "/illustrations/mnemonics/g5-u6795.svg",
    "label": "枕头",
    "alt": "枕字嵌在有横枝、直干和斜根的大树与轮廓像“冘”的故事道具组成的学习插图中"
  },
  "蚕": {
    "src": "/illustrations/mnemonics/g5-u8695.svg",
    "label": "蚕茧",
    "alt": "蚕字嵌在弯身的小虫与轮廓像“天”的故事道具组成的学习插图中"
  },
  "考": {
    "src": "/illustrations/mnemonics/g5-u8003.svg",
    "label": "考试",
    "alt": "考字嵌在轮廓像“耂”的故事道具与轮廓像“丂”的故事道具组成的学习插图中"
  },
  "疼": {
    "src": "/illustrations/mnemonics/g5-u75bc.svg",
    "label": "疼爱",
    "alt": "疼字嵌在轮廓像“疒”的故事道具与轮廓像“冬”的故事道具组成的学习插图中"
  },
  "席": {
    "src": "/illustrations/mnemonics/g5-u5e2d.svg",
    "label": "草席",
    "alt": "席字嵌在垂下的布幅与完整物象组成的学习插图中"
  },
  "糖": {
    "src": "/illustrations/mnemonics/g5-u7cd6.svg",
    "label": "糖果",
    "alt": "糖字嵌在米架和四散米粒与轮廓像“唐”的故事道具组成的学习插图中"
  },
  "屑": {
    "src": "/illustrations/mnemonics/g5-u5c51.svg",
    "label": "纸屑",
    "alt": "屑字嵌在轮廓像“尸”的故事道具与轮廓像“肖”的故事道具组成的学习插图中"
  },
  "钉": {
    "src": "/illustrations/mnemonics/g5-u9489.svg",
    "label": "钉子",
    "alt": "钉字嵌在金属工具架与轮廓像“丁”的故事道具组成的学习插图中"
  },
  "毕": {
    "src": "/illustrations/mnemonics/g5-u6bd5.svg",
    "label": "毕业",
    "alt": "毕字嵌在轮廓像“比”的故事道具与轮廓像“十”的故事道具组成的学习插图中"
  },
  "煮": {
    "src": "/illustrations/mnemonics/g5-u716e.svg",
    "label": "煮饭",
    "alt": "煮字嵌在四点温暖火光与轮廓像“者”的故事道具组成的学习插图中"
  },
  "腼": {
    "src": "/illustrations/mnemonics/g5-u817c.svg",
    "label": "腼腆",
    "alt": "腼字嵌在轮廓像“⺼”的故事道具与弯月形灯盘、轮廓像“面”的故事道具组成的学习插图中"
  },
  "腆": {
    "src": "/illustrations/mnemonics/g5-u8146.svg",
    "label": "腼腆",
    "alt": "腆字嵌在轮廓像“⺼”的故事道具与弯月形灯盘、轮廓像“典”的故事道具组成的学习插图中"
  },
  "誊": {
    "src": "/illustrations/mnemonics/g5-u8a8a.svg",
    "label": "誊写",
    "alt": "誊字嵌在从口中升起的言语与轮廓像“龹”的故事道具组成的学习插图中"
  },
  "励": {
    "src": "/illustrations/mnemonics/g5-u52b1.svg",
    "label": "鼓励",
    "alt": "励字嵌在弯曲而发力的手臂与轮廓像“厉”的故事道具组成的学习插图中"
  },
  "版": {
    "src": "/illustrations/mnemonics/g5-u7248.svg",
    "label": "出版",
    "alt": "版字嵌在轮廓像“片”的故事道具与轮廓像“反”的故事道具组成的学习插图中"
  },
  "祥": {
    "src": "/illustrations/mnemonics/g5-u7965.svg",
    "label": "吉祥",
    "alt": "祥字嵌在轮廓像“礻”的故事道具与对称羊角组成的学习插图中"
  },
  "歧": {
    "src": "/illustrations/mnemonics/g5-u6b67.svg",
    "label": "歧途",
    "alt": "歧字嵌在轮廓像“止”的故事道具与轮廓像“支”的故事道具组成的学习插图中"
  },
  "谨": {
    "src": "/illustrations/mnemonics/g5-u8c28.svg",
    "label": "谨慎",
    "alt": "谨字嵌在从说话框飞出的短句与轮廓像“堇”的故事道具组成的学习插图中"
  },
  "榆": {
    "src": "/illustrations/mnemonics/g5-u6986.svg",
    "label": "榆树",
    "alt": "榆字嵌在有横枝、直干和斜根的大树与轮廓像“俞”的故事道具组成的学习插图中"
  },
  "畔": {
    "src": "/illustrations/mnemonics/g5-u7554.svg",
    "label": "河畔",
    "alt": "畔字嵌在分成四格的田地与轮廓像“半”的故事道具组成的学习插图中"
  },
  "更": {
    "src": "/illustrations/mnemonics/g5-u66f4.svg",
    "label": "一更",
    "alt": "更字嵌在轮廓像“曰”的故事道具与轮廓像“一”的故事道具组成的学习插图中"
  },
  "聒": {
    "src": "/illustrations/mnemonics/g5-u8052.svg",
    "label": "聒噪",
    "alt": "聒字嵌在竖起的耳朵与轮廓像“舌”的故事道具组成的学习插图中"
  },
  "孙": {
    "src": "/illustrations/mnemonics/g5-u5b59.svg",
    "label": "子孙",
    "alt": "孙字嵌在被轻轻托住的孩子与中央光点与两侧小点组成的学习插图中"
  },
  "泊": {
    "src": "/illustrations/mnemonics/g5-u6cca.svg",
    "label": "停泊",
    "alt": "泊字嵌在三股清亮水流与明亮的小窗组成的学习插图中"
  },
  "愁": {
    "src": "/illustrations/mnemonics/g5-u6101.svg",
    "label": "发愁",
    "alt": "愁字嵌在心形灯带与三点微光与轮廓像“秋”的故事道具组成的学习插图中"
  },
  "寺": {
    "src": "/illustrations/mnemonics/g5-u5bfa.svg",
    "label": "寺庙",
    "alt": "寺字嵌在有刻度的手腕与分层的土台组成的学习插图中"
  },
  "桨": {
    "src": "/illustrations/mnemonics/g5-u6868.svg",
    "label": "船桨",
    "alt": "桨字嵌在有横枝、直干和斜根的大树与完整物象组成的学习插图中"
  },
  "桩": {
    "src": "/illustrations/mnemonics/g5-u6869.svg",
    "label": "木桩",
    "alt": "桩字嵌在有横枝、直干和斜根的大树与轮廓像“庄”的故事道具组成的学习插图中"
  },
  "暇": {
    "src": "/illustrations/mnemonics/g5-u6687.svg",
    "label": "闲暇",
    "alt": "暇字嵌在有中央光带的日轮与轮廓像“叚”的故事道具组成的学习插图中"
  },
  "榕": {
    "src": "/illustrations/mnemonics/g5-u6995.svg",
    "label": "榕树",
    "alt": "榕字嵌在有横枝、直干和斜根的大树与轮廓像“容”的故事道具组成的学习插图中"
  },
  "纠": {
    "src": "/illustrations/mnemonics/g5-u7ea0.svg",
    "label": "纠正",
    "alt": "纠字嵌在盘绕的细丝线与轮廓像“丩”的故事道具组成的学习插图中"
  },
  "耀": {
    "src": "/illustrations/mnemonics/g5-u8000.svg",
    "label": "闪耀",
    "alt": "耀字嵌在轮廓像“羽”的故事道具与轮廓像“光”的故事道具、轮廓像“翟”的故事道具组成的学习插图中"
  },
  "涨": {
    "src": "/illustrations/mnemonics/g5-u6da8.svg",
    "label": "涨潮",
    "alt": "涨字嵌在三股清亮水流与轮廓像“张”的故事道具组成的学习插图中"
  },
  "塔": {
    "src": "/illustrations/mnemonics/g5-u5854.svg",
    "label": "宝塔",
    "alt": "塔字嵌在分层的土台与轮廓像“荅”的故事道具组成的学习插图中"
  },
  "梢": {
    "src": "/illustrations/mnemonics/g5-u68a2.svg",
    "label": "树梢",
    "alt": "梢字嵌在有横枝、直干和斜根的大树与轮廓像“肖”的故事道具组成的学习插图中"
  },
  "眉": {
    "src": "/illustrations/mnemonics/g5-u7709.svg",
    "label": "眉毛",
    "alt": "眉字嵌在方框中的眼睛与轮廓像“𠃜”的故事道具组成的学习插图中"
  },
  "抛": {
    "src": "/illustrations/mnemonics/g5-u629b.svg",
    "label": "抛开",
    "alt": "抛字嵌在伸出并发力的手臂与轮廓像“𠠵”的故事道具组成的学习插图中"
  },
  "悄": {
    "src": "/illustrations/mnemonics/g5-u6084.svg",
    "label": "悄没声儿",
    "alt": "悄字嵌在跳动的心形灯带与轮廓像“肖”的故事道具组成的学习插图中"
  },
  "累": {
    "src": "/illustrations/mnemonics/g5-u7d2f.svg",
    "label": "累累",
    "alt": "累字嵌在盘绕的细丝线与分成四格的田地组成的学习插图中"
  },
  "嫦": {
    "src": "/illustrations/mnemonics/g5-u5ae6.svg",
    "label": "嫦娥",
    "alt": "嫦字嵌在照料幼苗的人影与轮廓像“常”的故事道具组成的学习插图中"
  },
  "娥": {
    "src": "/illustrations/mnemonics/g5-u5a25.svg",
    "label": "嫦娥",
    "alt": "娥字嵌在照料幼苗的人影与轮廓像“我”的故事道具组成的学习插图中"
  },
  "嫉": {
    "src": "/illustrations/mnemonics/g5-u5ac9.svg",
    "label": "嫉妒",
    "alt": "嫉字嵌在照料幼苗的人影与轮廓像“疾”的故事道具组成的学习插图中"
  },
  "妒": {
    "src": "/illustrations/mnemonics/g5-u5992.svg",
    "label": "嫉妒",
    "alt": "妒字嵌在照料幼苗的人影与轮廓像“户”的故事道具组成的学习插图中"
  },
  "瓷": {
    "src": "/illustrations/mnemonics/g5-u74f7.svg",
    "label": "瓷器",
    "alt": "瓷字嵌在轮廓像“瓦”的故事道具与轮廓像“次”的故事道具组成的学习插图中"
  },
  "耻": {
    "src": "/illustrations/mnemonics/g5-u803b.svg",
    "label": "羞耻",
    "alt": "耻字嵌在竖起的耳朵与轮廓像“止”的故事道具组成的学习插图中"
  },
  "识": {
    "src": "/illustrations/mnemonics/g5-u8bc6.svg",
    "label": "默而识之",
    "alt": "识字嵌在从说话框飞出的短句与轮廓像“只”的故事道具组成的学习插图中"
  },
  "寝": {
    "src": "/illustrations/mnemonics/g5-u5bdd.svg",
    "label": "就寝",
    "alt": "寝字嵌在安稳覆盖的屋顶与完整物象组成的学习插图中"
  },
  "矣": {
    "src": "/illustrations/mnemonics/g5-u77e3.svg",
    "label": "矣",
    "alt": "矣字嵌在轮廓像“矢”的故事道具与轮廓像“厶”的故事道具组成的学习插图中"
  },
  "岂": {
    "src": "/illustrations/mnemonics/g5-u5c82.svg",
    "label": "岂能",
    "alt": "岂字嵌在高低相连的山峰与轮廓像“己”的故事道具组成的学习插图中"
  },
  "诲": {
    "src": "/illustrations/mnemonics/g5-u8bf2.svg",
    "label": "教诲",
    "alt": "诲字嵌在从说话框飞出的短句与轮廓像“每”的故事道具组成的学习插图中"
  },
  "谓": {
    "src": "/illustrations/mnemonics/g5-u8c13.svg",
    "label": "所谓",
    "alt": "谓字嵌在从说话框飞出的短句与轮廓像“胃”的故事道具组成的学习插图中"
  },
  "诵": {
    "src": "/illustrations/mnemonics/g5-u8bf5.svg",
    "label": "诵读",
    "alt": "诵字嵌在从说话框飞出的短句与轮廓像“甬”的故事道具组成的学习插图中"
  },
  "舅": {
    "src": "/illustrations/mnemonics/g5-u8205.svg",
    "label": "舅舅",
    "alt": "舅字嵌在轮廓像“臼”的故事道具与轮廓像“男”的故事道具组成的学习插图中"
  },
  "宴": {
    "src": "/illustrations/mnemonics/g5-u5bb4.svg",
    "label": "宴会",
    "alt": "宴字嵌在安稳覆盖的屋顶与轮廓像“妟”的故事道具组成的学习插图中"
  },
  "斩": {
    "src": "/illustrations/mnemonics/g5-u65a9.svg",
    "label": "斩断",
    "alt": "斩字嵌在有轮轴的车架与轮廓像“斤”的故事道具组成的学习插图中"
  },
  "凯": {
    "src": "/illustrations/mnemonics/g5-u51ef.svg",
    "label": "凯旋",
    "alt": "凯字嵌在轮廓像“几”的故事道具与轮廓像“岂”的故事道具组成的学习插图中"
  },
  "葛": {
    "src": "/illustrations/mnemonics/g5-u845b.svg",
    "label": "葛布",
    "alt": "葛字嵌在成排草叶与花梗与轮廓像“曷”的故事道具组成的学习插图中"
  },
  "述": {
    "src": "/illustrations/mnemonics/g5-u8ff0.svg",
    "label": "讲述",
    "alt": "述字嵌在回转向前的小路与轮廓像“术”的故事道具组成的学习插图中"
  },
  "传": {
    "src": "/illustrations/mnemonics/g5-u4f20.svg",
    "label": "传记",
    "alt": "传字嵌在侧身站立的人与轮廓像“专”的故事道具组成的学习插图中"
  },
  "鲁": {
    "src": "/illustrations/mnemonics/g5-u9c81.svg",
    "label": "鲁莽",
    "alt": "鲁字嵌在有鳍和尾巴的鱼与有中央光带的日轮组成的学习插图中"
  },
  "煞": {
    "src": "/illustrations/mnemonics/g5-u715e.svg",
    "label": "煞气",
    "alt": "煞字嵌在四点温暖火光与完整物象组成的学习插图中"
  },
  "寇": {
    "src": "/illustrations/mnemonics/g5-u5bc7.svg",
    "label": "敌寇",
    "alt": "寇字嵌在安稳覆盖的屋顶与完整物象组成的学习插图中"
  },
  "贾": {
    "src": "/illustrations/mnemonics/g5-u8d3e.svg",
    "label": "商贾",
    "alt": "贾字嵌在被托起的贝壳与轮廓像“覀”的故事道具组成的学习插图中"
  },
  "卷": {
    "src": "/illustrations/mnemonics/g5-u5377.svg",
    "label": "试卷",
    "alt": "卷字嵌在轮廓像“㔾”的故事道具与轮廓像“龹”的故事道具组成的学习插图中"
  },
  "刊": {
    "src": "/illustrations/mnemonics/g5-u520a.svg",
    "label": "刊物",
    "alt": "刊字嵌在竖直刀刃与轮廓像“干”的故事道具组成的学习插图中"
  },
  "琐": {
    "src": "/illustrations/mnemonics/g5-u7410.svg",
    "label": "琐事",
    "alt": "琐字嵌在三层玉架与完整物象组成的学习插图中"
  },
  "呻": {
    "src": "/illustrations/mnemonics/g5-u547b.svg",
    "label": "呻吟",
    "alt": "呻字嵌在方形传声窗与轮廓像“申”的故事道具组成的学习插图中"
  },
  "某": {
    "src": "/illustrations/mnemonics/g5-u67d0.svg",
    "label": "某人",
    "alt": "某字嵌在有横枝、直干和斜根的大树与轮廓像“甘”的故事道具组成的学习插图中"
  },
  "津": {
    "src": "/illustrations/mnemonics/g5-u6d25.svg",
    "label": "天津",
    "alt": "津字嵌在三股清亮水流与轮廓像“聿”的故事道具组成的学习插图中"
  },
  "限": {
    "src": "/illustrations/mnemonics/g5-u9650.svg",
    "label": "限制",
    "alt": "限字嵌在高低相接的土坡与轮廓像“艮”的故事道具组成的学习插图中"
  },
  "统": {
    "src": "/illustrations/mnemonics/g5-u7edf.svg",
    "label": "统一",
    "alt": "统字嵌在盘绕的细丝线与轮廓像“充”的故事道具组成的学习插图中"
  },
  "朴": {
    "src": "/illustrations/mnemonics/g5-u6734.svg",
    "label": "朴实",
    "alt": "朴字嵌在有横枝、直干和斜根的大树与轮廓像“卜”的故事道具组成的学习插图中"
  },
  "喻": {
    "src": "/illustrations/mnemonics/g5-u55bb.svg",
    "label": "比喻",
    "alt": "喻字嵌在方形传声窗与轮廓像“俞”的故事道具组成的学习插图中"
  },
  "差": {
    "src": "/illustrations/mnemonics/g5-u5dee.svg",
    "label": "差事",
    "alt": "差字嵌在轮廓像“工”的故事道具与对称羊角组成的学习插图中"
  },
  "瘾": {
    "src": "/illustrations/mnemonics/g5-u763e.svg",
    "label": "上瘾",
    "alt": "瘾字嵌在轮廓像“疒”的故事道具与轮廓像“隐”的故事道具组成的学习插图中"
  },
  "奔": {
    "src": "/illustrations/mnemonics/g5-u5954.svg",
    "label": "奔向",
    "alt": "奔字嵌在正面伸展的人与轮廓像“卉”的故事道具组成的学习插图中"
  },
  "籍": {
    "src": "/illustrations/mnemonics/g5-u7c4d.svg",
    "label": "书籍",
    "alt": "籍字嵌在两簇竹叶与轮廓像“耤”的故事道具组成的学习插图中"
  },
  "饥": {
    "src": "/illustrations/mnemonics/g5-u9965.svg",
    "label": "饥饿",
    "alt": "饥字嵌在带盖的食器与轮廓像“几”的故事道具组成的学习插图中"
  },
  "偿": {
    "src": "/illustrations/mnemonics/g5-u507f.svg",
    "label": "补偿",
    "alt": "偿字嵌在侧身站立的人与轮廓像“尝”的故事道具组成的学习插图中"
  },
  "甸": {
    "src": "/illustrations/mnemonics/g5-u7538.svg",
    "label": "沉甸甸",
    "alt": "甸字嵌在分成四格的田地与轮廓像“勹”的故事道具组成的学习插图中"
  },
  "悟": {
    "src": "/illustrations/mnemonics/g5-u609f.svg",
    "label": "领悟",
    "alt": "悟字嵌在跳动的心形灯带与轮廓像“吾”的故事道具组成的学习插图中"
  },
  "馈": {
    "src": "/illustrations/mnemonics/g5-u9988.svg",
    "label": "反馈",
    "alt": "馈字嵌在带盖的食器与轮廓像“贵”的故事道具组成的学习插图中"
  },
  "磁": {
    "src": "/illustrations/mnemonics/g5-u78c1.svg",
    "label": "磁铁",
    "alt": "磁字嵌在带切面的岩石与轮廓像“兹”的故事道具组成的学习插图中"
  },
  "酵": {
    "src": "/illustrations/mnemonics/g5-u9175.svg",
    "label": "发酵",
    "alt": "酵字嵌在封口酒坛与轮廓像“孝”的故事道具组成的学习插图中"
  },
  "皎": {
    "src": "/illustrations/mnemonics/g5-u768e.svg",
    "label": "皎洁",
    "alt": "皎字嵌在明亮的小窗与轮廓像“交”的故事道具组成的学习插图中"
  },
  "鉴": {
    "src": "/illustrations/mnemonics/g5-u9274.svg",
    "label": "鉴赏",
    "alt": "鉴字嵌在金属工具架与完整物象组成的学习插图中"
  },
  "沥": {
    "src": "/illustrations/mnemonics/g5-u6ca5.svg",
    "label": "呕心沥血",
    "alt": "沥字嵌在三股清亮水流与轮廓像“历”的故事道具组成的学习插图中"
  }
} as const;

/* Generated by scripts/generate-grade5-catalog.mjs. Do not edit by hand. */
export const grade5LessonVisuals = {
  "g5v1-l01": {
    "src": "/illustrations/lessons/g5-01.jpg",
    "label": "白鹭",
    "alt": "清晨水田里的白鹭，留白宁静，羽毛与芦苇形成优雅节奏"
  },
  "g5v1-l02": {
    "src": "/illustrations/lessons/g5-02.jpg",
    "label": "落花生",
    "alt": "暖秋小院里一家人围坐谈花生，泥土、果实和灯火温厚朴素"
  },
  "g5v1-l03": {
    "src": "/illustrations/lessons/g5-03.jpg",
    "label": "桂花雨",
    "alt": "桂树下金色花雨纷飞，孩子举着竹箩，江南庭院温柔明亮"
  },
  "g5v1-l04": {
    "src": "/illustrations/lessons/g5-04.jpg",
    "label": "珍珠鸟",
    "alt": "书房窗边的珍珠鸟靠近少年，藤蔓与阳光营造安静信赖感"
  },
  "g5v1-l05": {
    "src": "/illustrations/lessons/g5-05.jpg",
    "label": "搭石",
    "alt": "山村清溪上的搭石，乡亲相让而行，水光清澈、动作有秩序"
  },
  "g5v1-l06": {
    "src": "/illustrations/lessons/g5-06.jpg",
    "label": "将相和",
    "alt": "古代宫廷与城门之间，两位人物从对峙走向并肩，庄重但儿童友好"
  },
  "g5v1-l07": {
    "src": "/illustrations/lessons/g5-07.jpg",
    "label": "什么比猎豹的速度更快",
    "alt": "横向速度赛道从猎豹延伸到火箭和光束，层级清楚、科学明快"
  },
  "g5v1-l08": {
    "src": "/illustrations/lessons/g5-08.jpg",
    "label": "冀中的地道战",
    "alt": "剖面式地道网络连接村庄，通风口、岔道和民众协作清晰可见"
  },
  "g5v1-l09": {
    "src": "/illustrations/lessons/g5-09.jpg",
    "label": "猎人海力布",
    "alt": "山谷村庄前，猎人警告乡亲远离灾害，神话气息而不惊悚"
  },
  "g5v1-l10": {
    "src": "/illustrations/lessons/g5-10.jpg",
    "label": "牛郎织女（一）",
    "alt": "月夜田野里青年与老牛相伴，远处织机星光，民间故事温暖梦幻"
  },
  "g5v1-l11": {
    "src": "/illustrations/lessons/g5-11.jpg",
    "label": "牛郎织女（二）",
    "alt": "星河之上鹊桥相连，两端人物遥望，蓝紫夜空柔和而有希望"
  },
  "g5v1-l12": {
    "src": "/illustrations/lessons/g5-12.jpg",
    "label": "古诗三首",
    "alt": "古卷上叠映山河、风雨与晨光，三幅诗境彼此呼应、含蓄庄重"
  },
  "g5v1-l13": {
    "src": "/illustrations/lessons/g5-13.jpg",
    "label": "少年中国说（节选）",
    "alt": "少年迎着朝阳站在山河前，鹰、江流与星光组成昂扬的象征画面"
  },
  "g5v1-l14": {
    "src": "/illustrations/lessons/g5-14.jpg",
    "label": "圆明园的毁灭",
    "alt": "画面一半是园林盛景、一半是冷静的残垣剪影，克制表达历史损失"
  },
  "g5v1-l15": {
    "src": "/illustrations/lessons/g5-15.jpg",
    "label": "小岛",
    "alt": "海防小岛上的菜地与营房，战士分享饭菜，海风强劲但画面温暖"
  },
  "g5v1-l16": {
    "src": "/illustrations/lessons/g5-16.jpg",
    "label": "太阳",
    "alt": "太阳光线连接地球上的水循环、植物与生活，儿童科学信息图风格"
  },
  "g5v1-l17": {
    "src": "/illustrations/lessons/g5-17.jpg",
    "label": "松鼠",
    "alt": "森林树杈上的松鼠与巢穴，尾巴蓬松，观察细节丰富而自然"
  },
  "g5v1-l18": {
    "src": "/illustrations/lessons/g5-18.jpg",
    "label": "慈母情深",
    "alt": "旧厂房柔光中母亲伏案工作，孩子握着书，真实克制、不苦情化"
  },
  "g5v1-l19": {
    "src": "/illustrations/lessons/g5-19.jpg",
    "label": "父爱之舟",
    "alt": "江南夜色中的小船载着父子和书箱，灯火映水，回忆感温柔含蓄"
  },
  "g5v1-l20": {
    "src": "/illustrations/lessons/g5-20.jpg",
    "label": "“精彩极了”和“糟糕透了”",
    "alt": "书桌两侧是温暖鼓励与冷静提醒，中间孩子修改作品，平衡而积极"
  },
  "g5v1-l21": {
    "src": "/illustrations/lessons/g5-21.jpg",
    "label": "古诗词三首",
    "alt": "秋山、江船与雪夜驿帐组成三联诗境，月色贯穿，清雅安静"
  },
  "g5v1-l22": {
    "src": "/illustrations/lessons/g5-22.jpg",
    "label": "鸟的天堂",
    "alt": "巨大的榕树垂根成林，晨光里群鸟飞起，小船从水面经过"
  },
  "g5v1-l23": {
    "src": "/illustrations/lessons/g5-23.jpg",
    "label": "月迹",
    "alt": "中秋庭院里孩子追寻月影，瓷盆、水面和树梢层层映月"
  },
  "g5v1-l24": {
    "src": "/illustrations/lessons/g5-24.jpg",
    "label": "古人谈读书",
    "alt": "古今书桌相连，孩子专心读书做笔记，眼到口到心到以图形呈现"
  },
  "g5v1-l25": {
    "src": "/illustrations/lessons/g5-25.jpg",
    "label": "忆读书",
    "alt": "书页化成时间长河，童年到老年的阅读剪影相连，明亮亲切"
  },
  "g5v1-l26": {
    "src": "/illustrations/lessons/g5-26.jpg",
    "label": "我的“长生果”",
    "alt": "知识树结出发光书果，孩子阅读时故事世界从书页生长出来"
  }
} as const;
