/* Generated by scripts/generate-grade5-catalog.mjs. Do not edit by hand. */
export const grade5CharacterVisuals = {
  "鹭": {
    "src": "/illustrations/mnemonics-v2/g5-u9e6d.webp",
    "label": "白鹭",
    "alt": "白鹭是羽毛洁白、常在水田和河滩活动的鸟 图中“路”与“鸟”按上下结构自然长成“鹭”。"
  },
  "嫌": {
    "src": "/illustrations/mnemonics-v2/g5-u5acc.webp",
    "label": "嫌弃",
    "alt": "嫌弃就是因为不喜欢而躲开或不愿接近 图中“女”与“兼”按左右结构自然长成“嫌”。"
  },
  "嵌": {
    "src": "/illustrations/mnemonics-v2/g5-u5d4c.webp",
    "label": "镶嵌",
    "alt": "镶嵌就是把一种材料牢牢装进另一种材料的空隙 图中“山”与“𣢟”按上下结构自然长成“嵌”。"
  },
  "匣": {
    "src": "/illustrations/mnemonics-v2/g5-u5323.webp",
    "label": "匣子",
    "alt": "匣子是有盖、用来收藏小物件的盒子 图中“匚”与“甲”按左三包围结构自然长成“匣”。"
  },
  "嗜": {
    "src": "/illustrations/mnemonics-v2/g5-u55dc.webp",
    "label": "嗜好",
    "alt": "嗜好指特别喜欢、常常愿意做的事情 图中“口”与“耆”按左右结构自然长成“嗜”。"
  },
  "宜": {
    "src": "/illustrations/mnemonics-v2/g5-u5b9c.webp",
    "label": "适宜",
    "alt": "适宜就是条件正合适，做起来恰到好处 图中“宀”与“且”按上下结构自然长成“宜”。"
  },
  "鹤": {
    "src": "/illustrations/mnemonics-v2/g5-u9e64.webp",
    "label": "白鹤",
    "alt": "白鹤是长腿、长颈、羽毛洁白的大型水鸟 图中“隺”与“鸟”按左右结构自然长成“鹤”。"
  },
  "朱": {
    "src": "/illustrations/mnemonics-v2/g5-u6731.webp",
    "label": "朱红",
    "alt": "朱红是鲜明而温暖、略带橙色的红 图中“未”与“㇒”按穿插结构自然长成“朱”。"
  },
  "框": {
    "src": "/illustrations/mnemonics-v2/g5-u6846.webp",
    "label": "画框",
    "alt": "画框是围在图画四周、保护并衬托画面的边框 图中“木”与“匡”按左右结构自然长成“框”。"
  },
  "哨": {
    "src": "/illustrations/mnemonics-v2/g5-u54e8.webp",
    "label": "口哨",
    "alt": "口哨既可以指用嘴吹出的声音，也可以指能吹响的小哨子 图中“口”与“肖”按左右结构自然长成“哨”。"
  },
  "恩": {
    "src": "/illustrations/mnemonics-v2/g5-u6069.webp",
    "label": "恩惠",
    "alt": "恩惠是别人给予的帮助和好处，值得记在心里 图中“因”与“心”按上下结构自然长成“恩”。"
  },
  "韵": {
    "src": "/illustrations/mnemonics-v2/g5-u97f5.webp",
    "label": "韵味",
    "alt": "韵味是声音、语言或事物中耐人回味的美感 图中“音”与“匀”按左右结构自然长成“韵”。"
  },
  "亩": {
    "src": "/illustrations/mnemonics-v2/g5-u4ea9.webp",
    "label": "半亩",
    "alt": "亩是计量土地面积的单位，常用来计算田地大小 图中“亠”与“田”按上下结构自然长成“亩”。"
  },
  "吩": {
    "src": "/illustrations/mnemonics-v2/g5-u5429.webp",
    "label": "吩咐",
    "alt": "吩通常和咐组成“吩咐”，表示把要做的事告诉别人 图中“口”与“分”按左右结构自然长成“吩”。"
  },
  "榨": {
    "src": "/illustrations/mnemonics-v2/g5-u69a8.webp",
    "label": "榨油",
    "alt": "榨油就是用压力把花生等原料里的油挤出来 图中“木”与“窄”按左右结构自然长成“榨”。"
  },
  "榴": {
    "src": "/illustrations/mnemonics-v2/g5-u69b4.webp",
    "label": "石榴",
    "alt": "石榴是一种果皮厚、里面有许多红色籽粒的水果 图中“木”与“留”按左右结构自然长成“榴”。"
  },
  "矮": {
    "src": "/illustrations/mnemonics-v2/g5-u77ee.webp",
    "label": "矮小",
    "alt": "矮小表示从下到上的高度比较低 图中“矢”与“委”按左右结构自然长成“矮”。"
  },
  "播": {
    "src": "/illustrations/mnemonics-v2/g5-u64ad.webp",
    "label": "播种",
    "alt": "播种就是把种子均匀撒进土里，让它们生长 图中“扌”与“番”按左右结构自然长成“播”。"
  },
  "浇": {
    "src": "/illustrations/mnemonics-v2/g5-u6d47.webp",
    "label": "浇水",
    "alt": "浇水就是让水流到植物或土地上 图中“氵”与“尧”按左右结构自然长成“浇”。"
  },
  "咐": {
    "src": "/illustrations/mnemonics-v2/g5-u5490.webp",
    "label": "吩咐",
    "alt": "咐和吩连用成“吩咐”，表示用话把任务交代清楚 图中“口”与“付”按左右结构自然长成“咐”。"
  },
  "亭": {
    "src": "/illustrations/mnemonics-v2/g5-u4ead.webp",
    "label": "茅亭",
    "alt": "茅亭是用茅草盖顶、供人停留休息的小建筑 图中“亠”与“口”与“冖”与“丁”按上下结构自然长成“亭”。"
  },
  "慕": {
    "src": "/illustrations/mnemonics-v2/g5-u6155.webp",
    "label": "爱慕",
    "alt": "爱慕就是因为欣赏而真心喜欢、向往 图中“莫”与“⺗”按上下结构自然长成“慕”。"
  },
  "谈": {
    "src": "/illustrations/mnemonics-v2/g5-u8c08.webp",
    "label": "谈论",
    "alt": "谈论就是几个人围绕一件事交换看法 图中“讠”与“炎”按左右结构自然长成“谈”。"
  },
  "箩": {
    "src": "/illustrations/mnemonics-v2/g5-u7ba9.webp",
    "label": "箩筐",
    "alt": "箩筐是用竹篾编成、用来盛东西的器具 图中“⺮”与“罗”按上下结构自然长成“箩”。"
  },
  "杭": {
    "src": "/illustrations/mnemonics-v2/g5-u676d.webp",
    "label": "杭州",
    "alt": "杭州是浙江省的一座城市，以西湖和江南风景闻名 图中“木”与“亢”按左右结构自然长成“杭”。"
  },
  "懂": {
    "src": "/illustrations/mnemonics-v2/g5-u61c2.webp",
    "label": "懂得",
    "alt": "懂得就是明白一件事的意思或道理 图中“忄”与“董”按左右结构自然长成“懂”。"
  },
  "兰": {
    "src": "/illustrations/mnemonics-v2/g5-u5170.webp",
    "label": "兰花",
    "alt": "兰花是叶片细长、花朵清雅的一类植物 图中“丷”与“三”按上下结构自然长成“兰”。"
  },
  "婆": {
    "src": "/illustrations/mnemonics-v2/g5-u5a46.webp",
    "label": "老婆婆",
    "alt": "外婆是母亲的母亲，是家庭中的长辈 图中“波”与“女”按上下结构自然长成“婆”。"
  },
  "糕": {
    "src": "/illustrations/mnemonics-v2/g5-u7cd5.webp",
    "label": "糕饼",
    "alt": "糕饼是用米、面等原料做成的点心 图中“米”与“羔”按左右结构自然长成“糕”。"
  },
  "饼": {
    "src": "/illustrations/mnemonics-v2/g5-u997c.webp",
    "label": "糕饼",
    "alt": "饼是用面粉、米粉等制成的扁圆形食物 图中“饣”与“并”按左右结构自然长成“饼”。"
  },
  "浸": {
    "src": "/illustrations/mnemonics-v2/g5-u6d78.webp",
    "label": "沉浸",
    "alt": "沉浸原指泡在水里，也常表示全心进入某种感受 图中“氵”与“彐”与“冖”与“又”按左右结构自然长成“浸”。"
  },
  "缠": {
    "src": "/illustrations/mnemonics-v2/g5-u7f20.webp",
    "label": "纠缠",
    "alt": "纠缠就是丝线或事情相互绕住，难以分开 图中“纟”与“㢆”按左右结构自然长成“缠”。"
  },
  "茶": {
    "src": "/illustrations/mnemonics-v2/g5-u8336.webp",
    "label": "茶叶",
    "alt": "茶叶是从茶树上采下并加工过的叶子 图中“艹”与“人”与“木”按上下结构自然长成“茶”。"
  },
  "捡": {
    "src": "/illustrations/mnemonics-v2/g5-u6361.webp",
    "label": "捡起",
    "alt": "捡起就是用手把地上的东西拿起来 图中“扌”与“佥”按左右结构自然长成“捡”。"
  },
  "蔓": {
    "src": "/illustrations/mnemonics-v2/g5-u8513.webp",
    "label": "蔓延",
    "alt": "蔓延表示像藤蔓一样不断向四周伸展 图中“艹”与“曼”按上下结构自然长成“蔓”。"
  },
  "幽": {
    "src": "/illustrations/mnemonics-v2/g5-u5e7d.webp",
    "label": "幽深",
    "alt": "幽深形容地方安静、深远，光线也比较暗 图中“幺”与“幺”与“山”按半包围结构自然长成“幽”。"
  },
  "悉": {
    "src": "/illustrations/mnemonics-v2/g5-u6089.webp",
    "label": "熟悉",
    "alt": "熟悉就是对人或事了解得很清楚，不感到陌生 图中“釆”与“心”按上下结构自然长成“悉”。"
  },
  "雏": {
    "src": "/illustrations/mnemonics-v2/g5-u96cf.webp",
    "label": "雏鸟",
    "alt": "雏鸟是刚孵出或还没有长大的小鸟 图中“刍”与“隹”按左右结构自然长成“雏”。"
  },
  "哟": {
    "src": "/illustrations/mnemonics-v2/g5-u54df.webp",
    "label": "哟",
    "alt": "哟是表示惊讶、提醒等语气的声音 图中“口”与“约”按左右结构自然长成“哟”。"
  },
  "柜": {
    "src": "/illustrations/mnemonics-v2/g5-u67dc.webp",
    "label": "书柜",
    "alt": "书柜是分层收藏和摆放书籍的柜子 图中“木”与“巨”按左右结构自然长成“柜”。"
  },
  "享": {
    "src": "/illustrations/mnemonics-v2/g5-u4eab.webp",
    "label": "享受",
    "alt": "享受就是从生活或活动中得到满足和愉快 图中“亠”与“口”与“子”按上中下结构自然长成“享”。"
  },
  "陪": {
    "src": "/illustrations/mnemonics-v2/g5-u966a.webp",
    "label": "陪伴",
    "alt": "陪伴就是留在别人身边，一起经历一段时间 图中“阝”与“咅”按左右结构自然长成“陪”。"
  },
  "趴": {
    "src": "/illustrations/mnemonics-v2/g5-u8db4.webp",
    "label": "趴下",
    "alt": "趴下就是身体朝下贴近地面或桌面 图中“⻊”与“八”按左右结构自然长成“趴”。"
  },
  "睑": {
    "src": "/illustrations/mnemonics-v2/g5-u7751.webp",
    "label": "眼睑",
    "alt": "眼睑就是眼睛外面能够开合的皮肤，也叫眼皮 图中“目”与“佥”按左右结构自然长成“睑”。"
  },
  "眸": {
    "src": "/illustrations/mnemonics-v2/g5-u7738.webp",
    "label": "眼眸",
    "alt": "眼眸指眼睛，尤其是眼珠和目光 图中“目”与“牟”按左右结构自然长成“眸”。"
  },
  "咂": {
    "src": "/illustrations/mnemonics-v2/g5-u5482.webp",
    "label": "咂嘴",
    "alt": "咂嘴是嘴唇开合并发出轻微声音的动作 图中“口”与“匝”按左右结构自然长成“咂”。"
  },
  "汛": {
    "src": "/illustrations/mnemonics-v2/g5-u6c5b.webp",
    "label": "汛期",
    "alt": "汛期是江河水位集中上涨、需要留意洪水的时段 图中“氵”与“卂”按左右结构自然长成“汛”。"
  },
  "挽": {
    "src": "/illustrations/mnemonics-v2/g5-u633d.webp",
    "label": "挽裤",
    "alt": "挽留就是拉住或劝说将要离开的人留下来 图中“扌”与“免”按左右结构自然长成“挽”。"
  },
  "间": {
    "src": "/illustrations/mnemonics-v2/g5-u95f4.webp",
    "label": "间隔",
    "alt": "间隔是两个事物之间留出的距离或时间 图中“门”与“日”按上三包围结构自然长成“间”。"
  },
  "惰": {
    "src": "/illustrations/mnemonics-v2/g5-u60f0.webp",
    "label": "懒惰",
    "alt": "懒惰就是不愿劳动或行动，总想少做事情 图中“忄”与“左”与“月”按左右结构自然长成“惰”。"
  },
  "衡": {
    "src": "/illustrations/mnemonics-v2/g5-u8861.webp",
    "label": "平衡",
    "alt": "平衡就是两边轻重、力量或状态保持相称 图中“彳”与“田”与“大”与“亍”按穿插结构自然长成“衡”。"
  },
  "协": {
    "src": "/illustrations/mnemonics-v2/g5-u534f.webp",
    "label": "协调",
    "alt": "协调就是不同部分互相配合，行动一致 图中“十”与“办”按左右结构自然长成“协”。"
  },
  "绰": {
    "src": "/illustrations/mnemonics-v2/g5-u7ef0.webp",
    "label": "人影绰绰",
    "alt": "绰绰有余表示数量或能力充足，用起来还有剩余 图中“纟”与“卓”按左右结构自然长成“绰”。"
  },
  "洪": {
    "src": "/illustrations/mnemonics-v2/g5-u6d2a.webp",
    "label": "洪水",
    "alt": "洪水是水位猛涨后漫出河道的大水 图中“氵”与“共”按左右结构自然长成“洪”。"
  },
  "访": {
    "src": "/illustrations/mnemonics-v2/g5-u8bbf.webp",
    "label": "访问",
    "alt": "访问就是有目的地去看望别人或了解情况 图中“讠”与“方”按左右结构自然长成“访”。"
  },
  "鞋": {
    "src": "/illustrations/mnemonics-v2/g5-u978b.webp",
    "label": "鞋子",
    "alt": "鞋子穿在脚上，用来保护脚并帮助行走 图中“革”与“圭”按左右结构自然长成“鞋”。"
  },
  "隔": {
    "src": "/illustrations/mnemonics-v2/g5-u9694.webp",
    "label": "间隔",
    "alt": "间隔也表示两个事物之间隔着一定距离 图中“阝”与“鬲”按左右结构自然长成“隔”。"
  },
  "懒": {
    "src": "/illustrations/mnemonics-v2/g5-u61d2.webp",
    "label": "懒惰",
    "alt": "懒惰是不愿意动脑或动手做应该做的事 图中“忄”与“赖”按左右结构自然长成“懒”。"
  },
  "稳": {
    "src": "/illustrations/mnemonics-v2/g5-u7a33.webp",
    "label": "安稳",
    "alt": "安稳就是平静、牢靠，不摇晃也不慌乱 图中“禾”与“急”按左右结构自然长成“稳”。"
  },
  "免": {
    "src": "/illustrations/mnemonics-v2/g5-u514d.webp",
    "label": "免得",
    "alt": "免得表示为了避免出现某种不希望的情况 图中“⺈”与“口”与“儿”按上下结构自然长成“免”。"
  },
  "璧": {
    "src": "/illustrations/mnemonics-v2/g5-u74a7.webp",
    "label": "和氏璧",
    "alt": "和氏璧是故事中非常珍贵的一块美玉 图中“辟”与“玉”按上下结构自然长成“璧”。"
  },
  "臣": {
    "src": "/illustrations/mnemonics-v2/g5-u81e3.webp",
    "label": "大臣",
    "alt": "大臣是在朝廷中担任重要职务、协助国君处理事务的人 图中“臣”按独体结构自然长成“臣”。"
  },
  "强": {
    "src": "/illustrations/mnemonics-v2/g5-u5f3a.webp",
    "label": "强迫",
    "alt": "强迫就是用压力逼别人做不愿意做的事 图中“弓”与“虽”按左右结构自然长成“强”。"
  },
  "诺": {
    "src": "/illustrations/mnemonics-v2/g5-u8bfa.webp",
    "label": "承诺",
    "alt": "承诺就是认真答应别人，并准备做到 图中“讠”与“若”按左右结构自然长成“诺”。"
  },
  "划": {
    "src": "/illustrations/mnemonics-v2/g5-u5212.webp",
    "label": "计划",
    "alt": "计划是事先想好要做什么、怎样做 图中“戈”与“刂”按左右结构自然长成“划”。"
  },
  "典": {
    "src": "/illustrations/mnemonics-v2/g5-u5178.webp",
    "label": "典礼",
    "alt": "典礼是按一定礼仪举行的隆重仪式 图中“曲”与“八”按上下结构自然长成“典”。"
  },
  "罪": {
    "src": "/illustrations/mnemonics-v2/g5-u7f6a.webp",
    "label": "得罪",
    "alt": "得罪就是言行使别人不高兴或受到冒犯 图中“罒”与“非”按上下结构自然长成“罪”。"
  },
  "廉": {
    "src": "/illustrations/mnemonics-v2/g5-u5ec9.webp",
    "label": "廉颇",
    "alt": "廉颇是《将相和》中的赵国名将 图中“广”与“兼”按左上包围结构自然长成“廉”。"
  },
  "抵": {
    "src": "/illustrations/mnemonics-v2/g5-u62b5.webp",
    "label": "抵御",
    "alt": "抵御就是挡住外来的攻击或压力 图中“扌”与“氐”按左右结构自然长成“抵”。"
  },
  "御": {
    "src": "/illustrations/mnemonics-v2/g5-u5fa1.webp",
    "label": "抵御",
    "alt": "抵御表示设法阻挡，不让危险继续前进 图中“彳”与“卸”按左右结构自然长成“御”。"
  },
  "辞": {
    "src": "/illustrations/mnemonics-v2/g5-u8f9e.webp",
    "label": "推辞",
    "alt": "推辞就是表示不接受某件事或某种安排 图中“舌”与“辛”按左右结构自然长成“辞”。"
  },
  "辱": {
    "src": "/illustrations/mnemonics-v2/g5-u8fb1.webp",
    "label": "侮辱",
    "alt": "侮辱是用言行伤害别人的尊严 图中“辰”与“寸”按左上包围结构自然长成“辱”。"
  },
  "擅": {
    "src": "/illustrations/mnemonics-v2/g5-u64c5.webp",
    "label": "擅长",
    "alt": "擅长就是在某件事上很有本领，做得熟练 图中“扌”与“亶”按左右结构自然长成“擅”。"
  },
  "缶": {
    "src": "/illustrations/mnemonics-v2/g5-u7f36.webp",
    "label": "击缶",
    "alt": "缶是古代盛水或酒的陶器，也可以敲击发声 图中“午”与“山”按上下结构自然长成“缶”。"
  },
  "卿": {
    "src": "/illustrations/mnemonics-v2/g5-u537f.webp",
    "label": "上卿",
    "alt": "上卿是古代地位很高的官职 图中“卯”按独体结构自然长成“卿”。"
  },
  "削": {
    "src": "/illustrations/mnemonics-v2/g5-u524a.webp",
    "label": "削弱",
    "alt": "削弱就是使力量、能力或影响变小 图中“肖”与“刂”按左右结构自然长成“削”。"
  },
  "袍": {
    "src": "/illustrations/mnemonics-v2/g5-u888d.webp",
    "label": "战袍",
    "alt": "战袍是古代将士作战时穿的长袍 图中“衤”与“包”按左右结构自然长成“袍”。"
  },
  "召": {
    "src": "/illustrations/mnemonics-v2/g5-u53ec.webp",
    "label": "召集",
    "alt": "召集就是通知许多人到同一个地方集合 图中“刀”与“口”按上下结构自然长成“召”。"
  },
  "议": {
    "src": "/illustrations/mnemonics-v2/g5-u8bae.webp",
    "label": "商议",
    "alt": "商议就是几个人一起讨论并想办法 图中“讠”与“义”按左右结构自然长成“议”。"
  },
  "缺": {
    "src": "/illustrations/mnemonics-v2/g5-u7f3a.webp",
    "label": "缺少",
    "alt": "缺少就是数量不够，或原来完整的东西少了一部分 图中“缶”与“夬”按左右结构自然长成“缺”。"
  },
  "宫": {
    "src": "/illustrations/mnemonics-v2/g5-u5bab.webp",
    "label": "王宫",
    "alt": "王宫是古代国王居住和处理政事的建筑群 图中“宀”与“吕”按上下结构自然长成“宫”。"
  },
  "献": {
    "src": "/illustrations/mnemonics-v2/g5-u732e.webp",
    "label": "献上",
    "alt": "献上就是恭敬地把物品或心意送给别人 图中“南”与“犬”按左右结构自然长成“献”。"
  },
  "承": {
    "src": "/illustrations/mnemonics-v2/g5-u627f.webp",
    "label": "承诺",
    "alt": "承诺也包含承担责任、认真做到的意思 图中“氶”与“三”按穿插结构自然长成“承”。"
  },
  "抄": {
    "src": "/illustrations/mnemonics-v2/g5-u6284.webp",
    "label": "抄写",
    "alt": "抄写就是照着文字重新写一遍 图中“扌”与“少”按左右结构自然长成“抄”。"
  },
  "怯": {
    "src": "/illustrations/mnemonics-v2/g5-u602f.webp",
    "label": "胆怯",
    "alt": "胆怯就是害怕、缺少勇气 图中“忄”与“去”按左右结构自然长成“怯”。"
  },
  "拒": {
    "src": "/illustrations/mnemonics-v2/g5-u62d2.webp",
    "label": "拒绝",
    "alt": "拒绝就是明确表示不接受或不同意 图中“扌”与“巨”按左右结构自然长成“拒”。"
  },
  "荆": {
    "src": "/illustrations/mnemonics-v2/g5-u8346.webp",
    "label": "荆条",
    "alt": "荆条是荆灌木细长而有韧性的枝条 图中“艹”与“刑”按左右结构自然长成“荆”。"
  },
  "鸵": {
    "src": "/illustrations/mnemonics-v2/g5-u9e35.webp",
    "label": "鸵鸟",
    "alt": "鸵鸟是不会飞、但奔跑速度很快的大型鸟 图中“鸟”与“它”按左右结构自然长成“鸵”。"
  },
  "赢": {
    "src": "/illustrations/mnemonics-v2/g5-u8d62.webp",
    "label": "赢家",
    "alt": "赢家是在比赛或较量中取得胜利的人 图中“𣎆”与“贝”按上下结构自然长成“赢”。"
  },
  "冠": {
    "src": "/illustrations/mnemonics-v2/g5-u51a0.webp",
    "label": "冠军",
    "alt": "冠军是在比赛中取得第一名的人或队伍 图中“冖”与“㝴”按上下结构自然长成“冠”。"
  },
  "俯": {
    "src": "/illustrations/mnemonics-v2/g5-u4fef.webp",
    "label": "俯冲",
    "alt": "俯冲就是从高处向下快速冲去 图中“亻”与“府”按左右结构自然长成“俯”。"
  },
  "喷": {
    "src": "/illustrations/mnemonics-v2/g5-u55b7.webp",
    "label": "喷气",
    "alt": "喷气就是气体从小口中快速冲出来 图中“口”与“贲”按左右结构自然长成“喷”。"
  },
  "枚": {
    "src": "/illustrations/mnemonics-v2/g5-u679a.webp",
    "label": "一枚",
    "alt": "枚是量词，可以用来数较小、形状相近的东西 图中“木”与“⺙”按左右结构自然长成“枚”。"
  },
  "箭": {
    "src": "/illustrations/mnemonics-v2/g5-u7bad.webp",
    "label": "火箭",
    "alt": "弓箭由弓和箭组成，箭射出后速度很快 图中“⺮”与“前”按上下结构自然长成“箭”。"
  },
  "浩": {
    "src": "/illustrations/mnemonics-v2/g5-u6d69.webp",
    "label": "浩瀚",
    "alt": "浩大形容水势、声势或规模非常大 图中“氵”与“告”按左右结构自然长成“浩”。"
  },
  "筒": {
    "src": "/illustrations/mnemonics-v2/g5-u7b52.webp",
    "label": "手电筒",
    "alt": "圆筒是上下粗细相近、内部中空的圆柱形物体 图中“⺮”与“同”按上下结构自然长成“筒”。"
  },
  "束": {
    "src": "/illustrations/mnemonics-v2/g5-u675f.webp",
    "label": "一束",
    "alt": "一束表示捆在一起的一把东西，也可以形容聚拢的光 图中“木”与“口”按穿插结构自然长成“束”。"
  },
  "赤": {
    "src": "/illustrations/mnemonics-v2/g5-u8d64.webp",
    "label": "赤道",
    "alt": "赤道是环绕地球中部、与南北两极距离相等的假想线 图中“赤”按独体结构自然长成“赤”。"
  },
  "圈": {
    "src": "/illustrations/mnemonics-v2/g5-u5708.webp",
    "label": "圆圈",
    "alt": "圆圈是首尾相连、没有棱角的环形 图中“囗”与“卷”按全包围结构自然长成“圈”。"
  },
  "置": {
    "src": "/illustrations/mnemonics-v2/g5-u7f6e.webp",
    "label": "难以置信",
    "alt": "位置表示人或物所在的地方 图中“罒”与“直”按上下结构自然长成“置”。"
  },
  "侵": {
    "src": "/illustrations/mnemonics-v2/g5-u4fb5.webp",
    "label": "侵略",
    "alt": "侵略是进入别国或别人的地方，强行侵犯权益 图中“亻”与“彐”与“冖”与“又”按左右结构自然长成“侵”。"
  },
  "略": {
    "src": "/illustrations/mnemonics-v2/g5-u7565.webp",
    "label": "侵略",
    "alt": "侵略指武力侵犯别国领土和人民 图中“田”与“各”按左右结构自然长成“略”。"
  },
  "垒": {
    "src": "/illustrations/mnemonics-v2/g5-u5792.webp",
    "label": "堡垒",
    "alt": "堡垒是用于防守的坚固建筑或工事 图中“厽”与“土”按上下结构自然长成“垒”。"
  },
  "任": {
    "src": "/illustrations/mnemonics-v2/g5-u4efb.webp",
    "label": "任丘",
    "alt": "任丘是河北省的一座城市，这里的“任”读rén 图中“亻”与“壬”按左右结构自然长成“任”。"
  },
  "丘": {
    "src": "/illustrations/mnemonics-v2/g5-u4e18.webp",
    "label": "任丘",
    "alt": "任丘是地名；丘也可以表示小土山 图中“斤”与“一”按上下结构自然长成“丘”。"
  },
  "搁": {
    "src": "/illustrations/mnemonics-v2/g5-u6401.webp",
    "label": "搁东西",
    "alt": "搁置就是把东西放下，暂时不处理 图中“扌”与“阁”按左右结构自然长成“搁”。"
  },
  "陷": {
    "src": "/illustrations/mnemonics-v2/g5-u9677.webp",
    "label": "陷坑",
    "alt": "陷坑是地面向下凹、容易使人或物掉进去的坑 图中“阝”与“臽”按左右结构自然长成“陷”。"
  },
  "拐": {
    "src": "/illustrations/mnemonics-v2/g5-u62d0.webp",
    "label": "拐弯",
    "alt": "拐弯就是离开原来的方向，转向另一边 图中“扌”与“另”按左右结构自然长成“拐”。"
  },
  "岔": {
    "src": "/illustrations/mnemonics-v2/g5-u5c94.webp",
    "label": "岔道",
    "alt": "岔道是从一条路分出去的另一条路 图中“分”与“山”按上下结构自然长成“岔”。"
  },
  "筑": {
    "src": "/illustrations/mnemonics-v2/g5-u7b51.webp",
    "label": "修筑",
    "alt": "修筑就是建造道路、工事或建筑 图中“⺮”与“巩”按上下结构自然长成“筑”。"
  },
  "堡": {
    "src": "/illustrations/mnemonics-v2/g5-u5821.webp",
    "label": "堡垒",
    "alt": "堡垒是为了防守而修建的坚固工事 图中“保”与“土”按上下结构自然长成“堡”。"
  },
  "党": {
    "src": "/illustrations/mnemonics-v2/g5-u515a.webp",
    "label": "党员",
    "alt": "党员是加入某一政党并遵守其章程的成员 图中“龸”与“兄”按穿插结构自然长成“党”。"
  },
  "妨": {
    "src": "/illustrations/mnemonics-v2/g5-u59a8.webp",
    "label": "妨碍",
    "alt": "妨碍就是挡住或影响别人，使事情不能顺利进行 图中“女”与“方”按左右结构自然长成“妨”。"
  },
  "蔽": {
    "src": "/illustrations/mnemonics-v2/g5-u853d.webp",
    "label": "隐蔽",
    "alt": "隐蔽就是借助遮挡把自己或物体藏起来 图中“艹”与“敝”按上下结构自然长成“蔽”。"
  },
  "酬": {
    "src": "/illustrations/mnemonics-v2/g5-u916c.webp",
    "label": "酬谢",
    "alt": "酬谢就是用财物、行动或话语感谢别人 图中“酉”与“州”按左右结构自然长成“酬”。"
  },
  "誓": {
    "src": "/illustrations/mnemonics-v2/g5-u8a93.webp",
    "label": "发誓",
    "alt": "发誓就是非常郑重地说出自己的决心或保证 图中“折”与“言”按上下结构自然长成“誓”。"
  },
  "谎": {
    "src": "/illustrations/mnemonics-v2/g5-u8c0e.webp",
    "label": "谎话",
    "alt": "谎话是不真实、故意欺骗别人的话 图中“讠”与“荒”按左右结构自然长成“谎”。"
  },
  "牺": {
    "src": "/illustrations/mnemonics-v2/g5-u727a.webp",
    "label": "牺牲",
    "alt": "牺牲是为了更重要的人或事情舍弃自己的利益，甚至生命 图中“牛”与“西”按左右结构自然长成“牺”。"
  },
  "珍": {
    "src": "/illustrations/mnemonics-v2/g5-u73cd.webp",
    "label": "珍宝",
    "alt": "珍宝是珍贵、值得好好保存的物品 图中“王”与“㐱”按左右结构自然长成“珍”。"
  },
  "叮": {
    "src": "/illustrations/mnemonics-v2/g5-u53ee.webp",
    "label": "叮嘱",
    "alt": "叮嘱就是反复、认真地提醒别人要记住某件事 图中“口”与“丁”按左右结构自然长成“叮”。"
  },
  "嘱": {
    "src": "/illustrations/mnemonics-v2/g5-u5631.webp",
    "label": "叮嘱",
    "alt": "叮嘱表示认真告诉别人应该怎样做，并希望他记住 图中“口”与“属”按左右结构自然长成“嘱”。"
  },
  "塌": {
    "src": "/illustrations/mnemonics-v2/g5-u584c.webp",
    "label": "倒塌",
    "alt": "倒塌就是建筑或堆放的东西向下坠落、失去支撑 图中“土”与“𦐇”按左右结构自然长成“塌”。"
  },
  "焦": {
    "src": "/illustrations/mnemonics-v2/g5-u7126.webp",
    "label": "焦急",
    "alt": "焦急就是心里非常着急，难以平静 图中“隹”与“灬”按上下结构自然长成“焦”。"
  },
  "延": {
    "src": "/illustrations/mnemonics-v2/g5-u5ef6.webp",
    "label": "延迟",
    "alt": "延迟就是比原定时间更晚发生或完成 图中“廴”与“丿”与“止”按上下结构自然长成“延”。"
  },
  "灾": {
    "src": "/illustrations/mnemonics-v2/g5-u707e.webp",
    "label": "灾难",
    "alt": "灾难是给生命、生活或环境造成严重损害的事情 图中“宀”与“火”按上下结构自然长成“灾”。"
  },
  "悔": {
    "src": "/illustrations/mnemonics-v2/g5-u6094.webp",
    "label": "后悔",
    "alt": "后悔是事后觉得原来的做法不对，希望能够改正 图中“忄”与“每”按左右结构自然长成“悔”。"
  },
  "扶": {
    "src": "/illustrations/mnemonics-v2/g5-u6276.webp",
    "label": "扶着老人",
    "alt": "扶持就是用手帮助别人站稳或继续前进 图中“扌”与“夫”按左右结构自然长成“扶”。"
  },
  "嫂": {
    "src": "/illustrations/mnemonics-v2/g5-u5ac2.webp",
    "label": "嫂子",
    "alt": "嫂子通常指哥哥的妻子 图中“女”与“叟”按左右结构自然长成“嫂”。"
  },
  "恳": {
    "src": "/illustrations/mnemonics-v2/g5-u6073.webp",
    "label": "勤勤恳恳",
    "alt": "恳求就是态度真诚、急切地请求别人 图中“艮”与“心”按上下结构自然长成“恳”。"
  },
  "筛": {
    "src": "/illustrations/mnemonics-v2/g5-u7b5b.webp",
    "label": "筛干草",
    "alt": "筛子是有许多小孔、用来分开粗细颗粒的工具 图中“⺮”与“师”按上下结构自然长成“筛”。"
  },
  "歹": {
    "src": "/illustrations/mnemonics-v2/g5-u6b79.webp",
    "label": "好歹",
    "alt": "歹人是做坏事、会伤害别人的人 图中“一”与“夕”按上下结构自然长成“歹”。"
  },
  "罕": {
    "src": "/illustrations/mnemonics-v2/g5-u7f55.webp",
    "label": "稀罕",
    "alt": "稀罕表示少见而让人觉得新奇，也可以表示喜爱 图中“⺳”与“干”按上下结构自然长成“罕”。"
  },
  "梭": {
    "src": "/illustrations/mnemonics-v2/g5-u68ad.webp",
    "label": "梭子",
    "alt": "梭子是织布时牵引纬线来回穿行的工具 图中“木”与“夋”按左右结构自然长成“梭”。"
  },
  "监": {
    "src": "/illustrations/mnemonics-v2/g5-u76d1.webp",
    "label": "监狱",
    "alt": "监狱是依法关押罪犯的地方 图中“〢”与“丿”与“一”与“丶”与“皿”按上下结构自然长成“监”。"
  },
  "狱": {
    "src": "/illustrations/mnemonics-v2/g5-u72f1.webp",
    "label": "监狱",
    "alt": "监狱是限制罪犯自由、依法执行刑罚的场所 图中“犭”与“讠”与“犬”按左右结构自然长成“狱”。"
  },
  "酿": {
    "src": "/illustrations/mnemonics-v2/g5-u917f.webp",
    "label": "酿的葡萄酒",
    "alt": "酿酒是让粮食或水果经过发酵变成酒 图中“酉”与“良”按左右结构自然长成“酿”。"
  },
  "瞌": {
    "src": "/illustrations/mnemonics-v2/g5-u778c.webp",
    "label": "瞌睡",
    "alt": "瞌睡是困倦得想闭上眼睛 图中“目”与“盍”按左右结构自然长成“瞌”。"
  },
  "落": {
    "src": "/illustrations/mnemonics-v2/g5-u843d.webp",
    "label": "落在后边",
    "alt": "“落在后边”表示没有跟上，位置到了后面；这里读là 图中“艹”与“洛”按上下结构自然长成“落”。"
  },
  "婚": {
    "src": "/illustrations/mnemonics-v2/g5-u5a5a.webp",
    "label": "结婚",
    "alt": "结婚是两个人依法建立夫妻关系 图中“女”与“昏”按左右结构自然长成“婚”。"
  },
  "郎": {
    "src": "/illustrations/mnemonics-v2/g5-u90ce.webp",
    "label": "牛郎",
    "alt": "牛郎是民间故事中的主要人物，也指故事里的年轻男子 图中“良”与“阝”按左右结构自然长成“郎”。"
  },
  "爹": {
    "src": "/illustrations/mnemonics-v2/g5-u7239.webp",
    "label": "爹娘",
    "alt": "爹是对父亲的口语称呼 图中“父”与“多”按上下结构自然长成“爹”。"
  },
  "辆": {
    "src": "/illustrations/mnemonics-v2/g5-u8f86.webp",
    "label": "车辆",
    "alt": "辆是量词，常用来数车 图中“车”与“两”按左右结构自然长成“辆”。"
  },
  "纱": {
    "src": "/illustrations/mnemonics-v2/g5-u7eb1.webp",
    "label": "纱衣",
    "alt": "纱是很细的丝线，也可以指用细线织成的轻薄织物 图中“纟”与“少”按左右结构自然长成“纱”。"
  },
  "妻": {
    "src": "/illustrations/mnemonics-v2/g5-u59bb.webp",
    "label": "妻子",
    "alt": "妻子是婚姻关系中的女性一方 图中“十”与“彐”与“女”按上下结构自然长成“妻”。"
  },
  "趟": {
    "src": "/illustrations/mnemonics-v2/g5-u8d9f.webp",
    "label": "一趟",
    "alt": "趟是量词，可以计算来回一次的行动 图中“走”与“尚”按左下包围结构自然长成“趟”。"
  },
  "托": {
    "src": "/illustrations/mnemonics-v2/g5-u6258.webp",
    "label": "托着纱衣",
    "alt": "托付就是把重要的人或事情交给可信任的人照管 图中“扌”与“乇”按左右结构自然长成“托”。"
  },
  "溜": {
    "src": "/illustrations/mnemonics-v2/g5-u6e9c.webp",
    "label": "溜出来",
    "alt": "溜走就是趁人不注意，悄悄而快速地离开 图中“氵”与“留”按左右结构自然长成“溜”。"
  },
  "辈": {
    "src": "/illustrations/mnemonics-v2/g5-u8f88.webp",
    "label": "一辈子",
    "alt": "长辈是年龄和辈分比自己高的人 图中“非”与“车”按上下结构自然长成“辈”。"
  },
  "挨": {
    "src": "/illustrations/mnemonics-v2/g5-u6328.webp",
    "label": "挨挨耳朵",
    "alt": "挨打表示身体受到击打；故事中要理解人物遭遇，不模仿伤害行为 图中“扌”与“矣”按左右结构自然长成“挨”。"
  },
  "俭": {
    "src": "/illustrations/mnemonics-v2/g5-u4fed.webp",
    "label": "节俭",
    "alt": "节俭就是生活有计划，不随意浪费物品和钱财 图中“亻”与“佥”按左右结构自然长成“俭”。"
  },
  "皇": {
    "src": "/illustrations/mnemonics-v2/g5-u7687.webp",
    "label": "富丽堂皇",
    "alt": "皇帝是中国古代国家的最高统治者 图中“白”与“王”按上下结构自然长成“皇”。"
  },
  "偎": {
    "src": "/illustrations/mnemonics-v2/g5-u504e.webp",
    "label": "依偎",
    "alt": "依偎就是亲近地靠在别人身旁 图中“亻”与“畏”按左右结构自然长成“偎”。"
  },
  "衰": {
    "src": "/illustrations/mnemonics-v2/g5-u8870.webp",
    "label": "衰老",
    "alt": "衰老表示身体机能随着年岁增长逐渐减弱 图中“衰”按独体结构自然长成“衰”。"
  },
  "珊": {
    "src": "/illustrations/mnemonics-v2/g5-u73ca.webp",
    "label": "珊瑚",
    "alt": "珊瑚是海中珊瑚虫形成的坚硬骨骼群体，形态像枝丛 图中“王”与“册”按左右结构自然长成“珊”。"
  },
  "瑚": {
    "src": "/illustrations/mnemonics-v2/g5-u745a.webp",
    "label": "珊瑚",
    "alt": "珊瑚常生活在温暖清澈的海水中，能形成珊瑚礁 图中“王”与“胡”按左右结构自然长成“瑚”。"
  },
  "礁": {
    "src": "/illustrations/mnemonics-v2/g5-u7901.webp",
    "label": "珊瑚礁",
    "alt": "暗礁是水面下不容易看见、可能影响航行的岩石 图中“石”与“焦”按左右结构自然长成“礁”。"
  },
  "筐": {
    "src": "/illustrations/mnemonics-v2/g5-u7b50.webp",
    "label": "两个筐",
    "alt": "竹筐是用竹条编成、可以盛放物品的器具 图中“⺮”与“匡”按上下结构自然长成“筐”。"
  },
  "拗": {
    "src": "/illustrations/mnemonics-v2/g5-u62d7.webp",
    "label": "拗不过",
    "alt": "执拗形容坚持自己的想法，不容易听进劝说 图中“扌”与“幼”按左右结构自然长成“拗”。"
  },
  "乃": {
    "src": "/illustrations/mnemonics-v2/g5-u4e43.webp",
    "label": "乃至",
    "alt": "乃是文言词，在不同句子中可以表示“是”“于是”等意思 图中“乃”按独体结构自然长成“乃”。"
  },
  "熏": {
    "src": "/illustrations/mnemonics-v2/g5-u718f.webp",
    "label": "熏陶",
    "alt": "熏陶比喻长期受到好思想、好习惯或文化的影响 图中“熏”按独体结构自然长成“熏”。"
  },
  "亥": {
    "src": "/illustrations/mnemonics-v2/g5-u4ea5.webp",
    "label": "己亥",
    "alt": "亥时是古代计时名称，大约相当于晚上九点到十一点 图中“人”按独体结构自然长成“亥”。"
  },
  "恃": {
    "src": "/illustrations/mnemonics-v2/g5-u6043.webp",
    "label": "恃强",
    "alt": "恃强就是依仗自己强大而欺压别人 图中“忄”与“寺”按左右结构自然长成“恃”。"
  },
  "擞": {
    "src": "/illustrations/mnemonics-v2/g5-u64de.webp",
    "label": "抖擞",
    "alt": "抖擞表示振作精神、显得有活力 图中“扌”与“数”按左右结构自然长成“擞”。"
  },
  "祭": {
    "src": "/illustrations/mnemonics-v2/g5-u796d.webp",
    "label": "祭祀",
    "alt": "祭祀是古人按照礼仪表达追思或敬意的活动 图中“月”与“又”与“示”按上下结构自然长成“祭”。"
  },
  "哀": {
    "src": "/illustrations/mnemonics-v2/g5-u54c0.webp",
    "label": "可哀",
    "alt": "哀伤就是因为失去、忧虑等感到深深悲伤 图中“衣”与“口”按穿插结构自然长成“哀”。"
  },
  "拘": {
    "src": "/illustrations/mnemonics-v2/g5-u62d8.webp",
    "label": "拘束",
    "alt": "拘束就是言行不自然，放不开 图中“扌”与“句”按左右结构自然长成“拘”。"
  },
  "泻": {
    "src": "/illustrations/mnemonics-v2/g5-u6cfb.webp",
    "label": "倾泻",
    "alt": "倾泻形容大量的水、光等快速向下流 图中“氵”与“写”按左右结构自然长成“泻”。"
  },
  "鳞": {
    "src": "/illustrations/mnemonics-v2/g5-u9cde.webp",
    "label": "鱼鳞",
    "alt": "鱼鳞是覆盖在鱼身体表面的薄片，能保护鱼体 图中“鱼”与“粦”按左右结构自然长成“鳞”。"
  },
  "惶": {
    "src": "/illustrations/mnemonics-v2/g5-u60f6.webp",
    "label": "惶恐",
    "alt": "惶恐就是心里害怕、非常不安 图中“忄”与“皇”按左右结构自然长成“惶”。"
  },
  "胎": {
    "src": "/illustrations/mnemonics-v2/g5-u80ce.webp",
    "label": "胎儿",
    "alt": "胎儿是在母体内尚未出生的孩子 图中“月”与“台”按左右结构自然长成“胎”。"
  },
  "履": {
    "src": "/illustrations/mnemonics-v2/g5-u5c65.webp",
    "label": "履行",
    "alt": "履行就是按照约定或责任认真去做 图中“尸”与“復”按左上包围结构自然长成“履”。"
  },
  "哉": {
    "src": "/illustrations/mnemonics-v2/g5-u54c9.webp",
    "label": "美哉",
    "alt": "哉是文言语气词，“美哉”就是“真美啊” 图中“𢦏”与“口”按右上包围结构自然长成“哉”。"
  },
  "潜": {
    "src": "/illustrations/mnemonics-v2/g5-u6f5c.webp",
    "label": "潜水",
    "alt": "潜水就是身体进入水面以下活动 图中“氵”与“替”按左右结构自然长成“潜”。"
  },
  "试": {
    "src": "/illustrations/mnemonics-v2/g5-u8bd5.webp",
    "label": "考试",
    "alt": "考试是通过答题、操作等方式检查学习成果 图中“讠”与“式”按左右结构自然长成“试”。"
  },
  "纵": {
    "src": "/illustrations/mnemonics-v2/g5-u7eb5.webp",
    "label": "纵横",
    "alt": "纵横表示竖向和横向，也形容交错广布 图中“纟”与“从”按左右结构自然长成“纵”。"
  },
  "疆": {
    "src": "/illustrations/mnemonics-v2/g5-u7586.webp",
    "label": "边疆",
    "alt": "边疆是靠近国界的地区 图中“弓”与“土”与“畺”按左右结构自然长成“疆”。"
  },
  "估": {
    "src": "/illustrations/mnemonics-v2/g5-u4f30.webp",
    "label": "估计",
    "alt": "估计是根据已有情况大致推测数量或结果 图中“亻”与“古”按左右结构自然长成“估”。"
  },
  "煌": {
    "src": "/illustrations/mnemonics-v2/g5-u714c.webp",
    "label": "辉煌",
    "alt": "辉煌形容光彩耀眼，也形容成就非常显著 图中“火”与“皇”按左右结构自然长成“煌”。"
  },
  "珑": {
    "src": "/illustrations/mnemonics-v2/g5-u73d1.webp",
    "label": "玲珑",
    "alt": "玲珑形容物体精巧细致，也可以形容灵活可爱 图中“王”与“龙”按左右结构自然长成“珑”。"
  },
  "剔": {
    "src": "/illustrations/mnemonics-v2/g5-u5254.webp",
    "label": "剔透",
    "alt": "剔透形容器物明亮透明、雕刻精细 图中“易”与“刂”按左右结构自然长成“剔”。"
  },
  "澜": {
    "src": "/illustrations/mnemonics-v2/g5-u6f9c.webp",
    "label": "安澜园",
    "alt": "波澜是较大的水波，也可以比喻事情的起伏变化 图中“氵”与“阑”按左右结构自然长成“澜”。"
  },
  "瑶": {
    "src": "/illustrations/mnemonics-v2/g5-u7476.webp",
    "label": "瑶台",
    "alt": "瑶台是传说中用美玉建成的台，也常用来形容美丽楼台 图中“王”与“爫”与“缶”按左右结构自然长成“瑶”。"
  },
  "陵": {
    "src": "/illustrations/mnemonics-v2/g5-u9675.webp",
    "label": "武陵春色",
    "alt": "陵园是安葬并纪念逝者的园地，应当保持庄重 图中“阝”与“夌”按左右结构自然长成“陵”。"
  },
  "宏": {
    "src": "/illustrations/mnemonics-v2/g5-u5b8f.webp",
    "label": "宏伟",
    "alt": "宏伟形容建筑、计划或气势规模很大 图中“宀”与“厷”按上下结构自然长成“宏”。"
  },
  "奉": {
    "src": "/illustrations/mnemonics-v2/g5-u5949.webp",
    "label": "奉命",
    "alt": "奉命就是接受命令并认真执行 图中“𡗗”按独体结构自然长成“奉”。"
  },
  "烬": {
    "src": "/illustrations/mnemonics-v2/g5-u70ec.webp",
    "label": "灰烬",
    "alt": "灰烬是物体燃烧后留下的灰和少量未烧尽物 图中“火”与“尽”按左右结构自然长成“烬”。"
  },
  "毁": {
    "src": "/illustrations/mnemonics-v2/g5-u6bc1.webp",
    "label": "毁灭",
    "alt": "毁灭就是严重破坏，使原有事物不复存在 图中“臼”与“工”与“殳”按左右结构自然长成“毁”。"
  },
  "损": {
    "src": "/illustrations/mnemonics-v2/g5-u635f.webp",
    "label": "损失",
    "alt": "损失是失去原有的人、财物、机会或价值 图中“扌”与“员”按左右结构自然长成“损”。"
  },
  "拱": {
    "src": "/illustrations/mnemonics-v2/g5-u62f1.webp",
    "label": "众星拱月",
    "alt": "拱桥是桥身向上弯成弧形的桥 图中“扌”与“共”按左右结构自然长成“拱”。"
  },
  "辉": {
    "src": "/illustrations/mnemonics-v2/g5-u8f89.webp",
    "label": "辉煌",
    "alt": "辉煌中的“辉”表示明亮闪耀的光彩 图中“光”与“军”按左右结构自然长成“辉”。"
  },
  "殿": {
    "src": "/illustrations/mnemonics-v2/g5-u6bbf.webp",
    "label": "宫殿",
    "alt": "宫殿是古代帝王处理政事、居住或举行仪式的大型建筑 图中“𡱒”与“殳”按左右结构自然长成“殿”。"
  },
  "览": {
    "src": "/illustrations/mnemonics-v2/g5-u89c8.webp",
    "label": "游览",
    "alt": "游览就是从容地观看风景、建筑或展览 图中“〢”与“丿”与“一”与“丶”与“见”按上下结构自然长成“览”。"
  },
  "境": {
    "src": "/illustrations/mnemonics-v2/g5-u5883.webp",
    "label": "幻想的境界",
    "alt": "环境是人或事物周围的自然条件和社会条件 图中“土”与“竟”按左右结构自然长成“境”。"
  },
  "唐": {
    "src": "/illustrations/mnemonics-v2/g5-u5510.webp",
    "label": "唐代",
    "alt": "唐代是中国历史上的一个朝代 图中“广”与“肀”与“口”按左上包围结构自然长成“唐”。"
  },
  "闯": {
    "src": "/illustrations/mnemonics-v2/g5-u95ef.webp",
    "label": "闯入",
    "alt": "闯入就是未经允许或不顾阻拦突然进入 图中“门”与“马”按上三包围结构自然长成“闯”。"
  },
  "销": {
    "src": "/illustrations/mnemonics-v2/g5-u9500.webp",
    "label": "销毁",
    "alt": "销毁就是把物品彻底毁掉，使它不能再使用 图中“钅”与“肖”按左右结构自然长成“销”。"
  },
  "瞒": {
    "src": "/illustrations/mnemonics-v2/g5-u7792.webp",
    "label": "隐瞒",
    "alt": "隐瞒就是知道事实却故意不告诉别人 图中“目”与“艹”与“两”按左右结构自然长成“瞒”。"
  },
  "域": {
    "src": "/illustrations/mnemonics-v2/g5-u57df.webp",
    "label": "海域",
    "alt": "海域是一定范围内的海洋水面和水体 图中“土”与“或”按左右结构自然长成“域”。"
  },
  "艇": {
    "src": "/illustrations/mnemonics-v2/g5-u8247.webp",
    "label": "小艇",
    "alt": "小艇是体形较小、在水上行驶的船 图中“舟”与“廷”按左右结构自然长成“艇”。"
  },
  "矛": {
    "src": "/illustrations/mnemonics-v2/g5-u77db.webp",
    "label": "矛盾",
    "alt": "矛是古代一种有长柄和尖头的兵器 图中“矛”按独体结构自然长成“矛”。"
  },
  "盾": {
    "src": "/illustrations/mnemonics-v2/g5-u76fe.webp",
    "label": "矛盾",
    "alt": "盾是用来遮挡和防护的器具 图中“⺁”与“十”与“目”按左上包围结构自然长成“盾”。"
  },
  "筷": {
    "src": "/illustrations/mnemonics-v2/g5-u7b77.webp",
    "label": "筷子",
    "alt": "筷子是一双细长餐具，用来夹取食物 图中“⺮”与“快”按上下结构自然长成“筷”。"
  },
  "炊": {
    "src": "/illustrations/mnemonics-v2/g5-u708a.webp",
    "label": "炊事员",
    "alt": "炊烟是做饭烧火时升起的烟 图中“火”与“欠”按左右结构自然长成“炊”。"
  },
  "哼": {
    "src": "/illustrations/mnemonics-v2/g5-u54fc.webp",
    "label": "哼",
    "alt": "课文里的“哼！”表示不满或不赞同，这里读hng 图中“口”与“亨”按左右结构自然长成“哼”。"
  },
  "喉": {
    "src": "/illustrations/mnemonics-v2/g5-u5589.webp",
    "label": "喉咙",
    "alt": "喉咙是颈部里面连接口腔、气管和食管的部位 图中“口”与“侯”按左右结构自然长成“喉”。"
  },
  "咙": {
    "src": "/illustrations/mnemonics-v2/g5-u5499.webp",
    "label": "喉咙",
    "alt": "喉咙是呼吸、吞咽和发声都会经过的部位 图中“口”与“龙”按左右结构自然长成“咙”。"
  },
  "哽": {
    "src": "/illustrations/mnemonics-v2/g5-u54fd.webp",
    "label": "哽咽",
    "alt": "哽咽是因为激动或难过而一时说不出完整的话 图中“口”与“更”按左右结构自然长成“哽”。"
  },
  "勺": {
    "src": "/illustrations/mnemonics-v2/g5-u52fa.webp",
    "label": "勺子",
    "alt": "勺子是有小凹槽和长柄、用来舀取东西的器具 图中“勹”与“丶”按右上包围结构自然长成“勺”。"
  },
  "搅": {
    "src": "/illustrations/mnemonics-v2/g5-u6405.webp",
    "label": "搅了几下",
    "alt": "搅拌就是用工具来回转动，使材料混合均匀 图中“扌”与“觉”按左右结构自然长成“搅”。"
  },
  "舀": {
    "src": "/illustrations/mnemonics-v2/g5-u8200.webp",
    "label": "舀起一勺汤",
    "alt": "舀水就是用勺、瓢等器具把水取出来 图中“爫”与“臼”按上下结构自然长成“舀”。"
  },
  "摄": {
    "src": "/illustrations/mnemonics-v2/g5-u6444.webp",
    "label": "摄氏",
    "alt": "摄氏是一种温度计量方法，符号通常写作℃ 图中“扌”与“聂”按左右结构自然长成“摄”。"
  },
  "殖": {
    "src": "/illustrations/mnemonics-v2/g5-u6b96.webp",
    "label": "繁殖",
    "alt": "繁殖是生物产生新个体，使种群延续 图中“歹”与“直”按左右结构自然长成“殖”。"
  },
  "炭": {
    "src": "/illustrations/mnemonics-v2/g5-u70ad.webp",
    "label": "煤炭",
    "alt": "煤炭是古代植物遗体经过漫长地质变化形成的燃料 图中“山”与“灰”按上下结构自然长成“炭”。"
  },
  "疗": {
    "src": "/illustrations/mnemonics-v2/g5-u7597.webp",
    "label": "治疗",
    "alt": "治疗就是用合适的方法帮助疾病或伤痛好转 图中“疒”与“了”按左上包围结构自然长成“疗”。"
  },
  "氏": {
    "src": "/illustrations/mnemonics-v2/g5-u6c0f.webp",
    "label": "摄氏",
    "alt": "摄氏中的“氏”来自科学家摄尔修斯姓氏的译名 图中“氏”按独体结构自然长成“氏”。"
  },
  "粮": {
    "src": "/illustrations/mnemonics-v2/g5-u7cae.webp",
    "label": "粮食",
    "alt": "粮食是供人食用的谷物、豆类和薯类等食物原料 图中“米”与“良”按左右结构自然长成“粮”。"
  },
  "区": {
    "src": "/illustrations/mnemonics-v2/g5-u533a.webp",
    "label": "地区",
    "alt": "地区是具有一定范围的地方 图中“匸”与“乂”按左三包围结构自然长成“区”。"
  },
  "杀": {
    "src": "/illustrations/mnemonics-v2/g5-u6740.webp",
    "label": "杀菌",
    "alt": "杀菌就是消灭或减少有害细菌；生活中要按安全方法操作 图中“乂”与“朩”按上下结构自然长成“杀”。"
  },
  "菌": {
    "src": "/illustrations/mnemonics-v2/g5-u83cc.webp",
    "label": "杀菌",
    "alt": "细菌是非常微小的生物，需要借助显微镜观察 图中“艹”与“囷”按上下结构自然长成“菌”。"
  },
  "驯": {
    "src": "/illustrations/mnemonics-v2/g5-u9a6f.webp",
    "label": "驯良",
    "alt": "驯良形容动物温顺，容易亲近，也愿意听从人的引导 图中“马”与“川”按左右结构自然长成“驯”。"
  },
  "矫": {
    "src": "/illustrations/mnemonics-v2/g5-u77eb.webp",
    "label": "矫健",
    "alt": "矫健形容动作有力、灵活，姿态挺拔 图中“矢”与“乔”按左右结构自然长成“矫”。"
  },
  "歇": {
    "src": "/illustrations/mnemonics-v2/g5-u6b47.webp",
    "label": "歇息",
    "alt": "歇息就是暂时停下活动，让身体恢复精神 图中“曷”与“欠”按左右结构自然长成“歇”。"
  },
  "杈": {
    "src": "/illustrations/mnemonics-v2/g5-u6748.webp",
    "label": "树杈",
    "alt": "树杈是树干或较粗树枝分出的枝杈 图中“木”与“叉”按左右结构自然长成“杈”。"
  },
  "藓": {
    "src": "/illustrations/mnemonics-v2/g5-u85d3.webp",
    "label": "苔藓",
    "alt": "苔藓是一类贴着潮湿地面或树皮生长的绿色小植物 图中“艹”与“鲜”按上下结构自然长成“藓”。"
  },
  "狭": {
    "src": "/illustrations/mnemonics-v2/g5-u72ed.webp",
    "label": "狭窄",
    "alt": "狭窄表示宽度小，能通过的空间不大 图中“犭”与“夹”按左右结构自然长成“狭”。"
  },
  "勉": {
    "src": "/illustrations/mnemonics-v2/g5-u52c9.webp",
    "label": "勉强",
    "alt": "勉强表示能力或条件不够，却仍尽力去做 图中“免”与“力”按左下包围结构自然长成“勉”。"
  },
  "锥": {
    "src": "/illustrations/mnemonics-v2/g5-u9525.webp",
    "label": "圆锥",
    "alt": "圆锥是一头尖、一头圆而较宽的立体形状 图中“钅”与“隹”按左右结构自然长成“锥”。"
  },
  "鼠": {
    "src": "/illustrations/mnemonics-v2/g5-u9f20.webp",
    "label": "松鼠",
    "alt": "松鼠是一种尾巴蓬松、善于攀爬和跳跃的小动物 图中“鼠”按独体结构自然长成“鼠”。"
  },
  "秀": {
    "src": "/illustrations/mnemonics-v2/g5-u79c0.webp",
    "label": "清秀",
    "alt": "清秀形容外表清爽、秀丽，让人感到舒服 图中“禾”与“乃”按上下结构自然长成“秀”。"
  },
  "玲": {
    "src": "/illustrations/mnemonics-v2/g5-u73b2.webp",
    "label": "玲珑",
    "alt": "玲珑形容物体精巧细致，也形容人灵活可爱 图中“王”与“令”按左右结构自然长成“玲”。"
  },
  "帽": {
    "src": "/illustrations/mnemonics-v2/g5-u5e3d.webp",
    "label": "帽子",
    "alt": "帽子戴在头上，可以保暖、遮阳或起装饰作用 图中“巾”与“冒”按左右结构自然长成“帽”。"
  },
  "尾": {
    "src": "/illustrations/mnemonics-v2/g5-u5c3e.webp",
    "label": "尾巴",
    "alt": "尾巴长在动物身体末端，能帮助保持平衡或传递信号 图中“尸”与“毛”按左上包围结构自然长成“尾”。"
  },
  "窝": {
    "src": "/illustrations/mnemonics-v2/g5-u7a9d.webp",
    "label": "鸟窝",
    "alt": "鸟窝是鸟用树枝、草叶等搭成的栖息和育雏处 图中“穴”与“呙”按上下结构自然长成“窝”。"
  },
  "滑": {
    "src": "/illustrations/mnemonics-v2/g5-u6ed1.webp",
    "label": "光滑",
    "alt": "光滑形容物体表面平整，没有明显的粗糙和阻碍 图中“氵”与“骨”按左右结构自然长成“滑”。"
  },
  "拾": {
    "src": "/illustrations/mnemonics-v2/g5-u62fe.webp",
    "label": "拾取",
    "alt": "拾取就是用手把地上或散落的东西拿起来 图中“扌”与“合”按左右结构自然长成“拾”。"
  },
  "梳": {
    "src": "/illustrations/mnemonics-v2/g5-u68b3.webp",
    "label": "梳理",
    "alt": "梳理就是用梳子把头发或毛发整理整齐 图中“木”与“㐬”按左右结构自然长成“梳”。"
  },
  "魄": {
    "src": "/illustrations/mnemonics-v2/g5-u9b44.webp",
    "label": "魂魄",
    "alt": "魂魄在课文语境中表示人的精神和心神 图中“白”与“鬼”按左右结构自然长成“魄”。"
  },
  "抑": {
    "src": "/illustrations/mnemonics-v2/g5-u6291.webp",
    "label": "压抑",
    "alt": "压抑形容心情或感情受到压制，不能自然表达 图中“扌”与“卬”按左右结构自然长成“抑”。"
  },
  "颓": {
    "src": "/illustrations/mnemonics-v2/g5-u9893.webp",
    "label": "颓败",
    "alt": "颓败形容衰落、破败，失去原有的精神或样子 图中“秃”与“页”按左右结构自然长成“颓”。"
  },
  "纫": {
    "src": "/illustrations/mnemonics-v2/g5-u7eab.webp",
    "label": "缝纫",
    "alt": "缝纫就是用针线把布料连接或缝制成衣物 图中“纟”与“刃”按左右结构自然长成“纫”。"
  },
  "噪": {
    "src": "/illustrations/mnemonics-v2/g5-u566a.webp",
    "label": "噪声",
    "alt": "噪声是嘈杂、刺耳或妨碍人正常活动的声音 图中“口”与“喿”按左右结构自然长成“噪”。"
  },
  "褐": {
    "src": "/illustrations/mnemonics-v2/g5-u8910.webp",
    "label": "褐色",
    "alt": "褐色是一种接近树皮、泥土的棕色 图中“衤”与“曷”按左右结构自然长成“褐”。"
  },
  "惫": {
    "src": "/illustrations/mnemonics-v2/g5-u60eb.webp",
    "label": "疲惫",
    "alt": "疲惫就是身体和精神都很累，需要休息 图中“备”与“心”按上下结构自然长成“惫”。"
  },
  "耽": {
    "src": "/illustrations/mnemonics-v2/g5-u803d.webp",
    "label": "耽误",
    "alt": "耽误就是因为拖延或受阻而错过时间、影响事情 图中“耳”与“冘”按左右结构自然长成“耽”。"
  },
  "兜": {
    "src": "/illustrations/mnemonics-v2/g5-u515c.webp",
    "label": "衣兜",
    "alt": "衣兜是衣服上用来装小物品的口袋 图中“兜”按独体结构自然长成“兜”。"
  },
  "权": {
    "src": "/illustrations/mnemonics-v2/g5-u6743.webp",
    "label": "权利",
    "alt": "权利是依法或依照规则可以做某件事、享有某种利益的资格 图中“木”与“又”按左右结构自然长成“权”。"
  },
  "碌": {
    "src": "/illustrations/mnemonics-v2/g5-u788c.webp",
    "label": "忙碌",
    "alt": "忙碌形容事情多，手脚不停，很少有空闲 图中“石”与“录”按左右结构自然长成“碌”。"
  },
  "吊": {
    "src": "/illustrations/mnemonics-v2/g5-u540a.webp",
    "label": "吊起",
    "alt": "吊起就是用绳索等把物体悬在空中或向上提起 图中“口”与“巾”按上下结构自然长成“吊”。"
  },
  "酷": {
    "src": "/illustrations/mnemonics-v2/g5-u9177.webp",
    "label": "酷暑",
    "alt": "酷暑是天气非常炎热的时节 图中“酉”与“告”按左右结构自然长成“酷”。"
  },
  "暑": {
    "src": "/illustrations/mnemonics-v2/g5-u6691.webp",
    "label": "酷暑",
    "alt": "暑表示炎热的季节或天气，如酷暑、暑假 图中“日”与“者”按上下结构自然长成“暑”。"
  },
  "脊": {
    "src": "/illustrations/mnemonics-v2/g5-u810a.webp",
    "label": "脊背",
    "alt": "脊背是人或动物躯干后面中央的一条骨肉区域 图中“脊”按独体结构自然长成“脊”。"
  },
  "罩": {
    "src": "/illustrations/mnemonics-v2/g5-u7f69.webp",
    "label": "笼罩",
    "alt": "笼罩就是像网、雾或光一样从上面覆盖住 图中“罒”与“卓”按上下结构自然长成“罩”。"
  },
  "竟": {
    "src": "/illustrations/mnemonics-v2/g5-u7adf.webp",
    "label": "竟然",
    "alt": "竟然表示事情出乎原先的意料 图中“音”与“儿”按上下结构自然长成“竟”。"
  },
  "哇": {
    "src": "/illustrations/mnemonics-v2/g5-u54c7.webp",
    "label": "好哇",
    "alt": "哇是表示惊讶、赞叹等语气的声音 图中“口”与“圭”按左右结构自然长成“哇”。"
  },
  "忍": {
    "src": "/illustrations/mnemonics-v2/g5-u5fcd.webp",
    "label": "忍受",
    "alt": "忍受就是遇到困难或痛苦时暂时承受住 图中“刃”与“心”按上下结构自然长成“忍”。"
  },
  "械": {
    "src": "/illustrations/mnemonics-v2/g5-u68b0.webp",
    "label": "机械",
    "alt": "机械是利用零件和动力完成工作的装置 图中“木”与“戒”按左右结构自然长成“械”。"
  },
  "酸": {
    "src": "/illustrations/mnemonics-v2/g5-u9178.webp",
    "label": "心酸",
    "alt": "心酸形容心里难过；“酸”也可以表示一种基本味道 图中“酉”与“夋”按左右结构自然长成“酸”。"
  },
  "茧": {
    "src": "/illustrations/mnemonics-v2/g5-u8327.webp",
    "label": "蚕茧",
    "alt": "蚕茧是蚕吐丝包住自己形成的椭圆形外壳 图中“艹”与“虫”按上下结构自然长成“茧”。"
  },
  "栈": {
    "src": "/illustrations/mnemonics-v2/g5-u6808.webp",
    "label": "客栈",
    "alt": "客栈是旧时供旅客住宿的地方，类似旅店 图中“木”与“戋”按左右结构自然长成“栈”。"
  },
  "冤": {
    "src": "/illustrations/mnemonics-v2/g5-u51a4.webp",
    "label": "冤枉",
    "alt": "冤枉是没有事实根据却被错误责怪或受到不公平对待 图中“冖”与“兔”按上下结构自然长成“冤”。"
  },
  "枉": {
    "src": "/illustrations/mnemonics-v2/g5-u6789.webp",
    "label": "冤枉",
    "alt": "冤枉中的“枉”表示歪曲事实，使人受到不公平对待 图中“木”与“王”按左右结构自然长成“枉”。"
  },
  "恍": {
    "src": "/illustrations/mnemonics-v2/g5-u604d.webp",
    "label": "恍惚",
    "alt": "恍惚形容注意力不集中，神志或感觉不清楚 图中“忄”与“光”按左右结构自然长成“恍”。"
  },
  "惚": {
    "src": "/illustrations/mnemonics-v2/g5-u60da.webp",
    "label": "恍惚",
    "alt": "恍惚表示精神不集中，眼前和心里的感觉都不清晰 图中“忄”与“忽”按左右结构自然长成“惚”。"
  },
  "跷": {
    "src": "/illustrations/mnemonics-v2/g5-u8df7.webp",
    "label": "跷跷板",
    "alt": "跷跷板是一种两端轮流升降的儿童游戏设施 图中“⻊”与“尧”按左右结构自然长成“跷”。"
  },
  "僻": {
    "src": "/illustrations/mnemonics-v2/g5-u50fb.webp",
    "label": "偏僻",
    "alt": "偏僻形容地方离主要道路或人群较远，来往不方便 图中“亻”与“辟”按左右结构自然长成“僻”。"
  },
  "委": {
    "src": "/illustrations/mnemonics-v2/g5-u59d4.webp",
    "label": "委屈",
    "alt": "委屈是受到不公平对待或误解时产生的难过感受 图中“禾”与“女”按上下结构自然长成“委”。"
  },
  "迪": {
    "src": "/illustrations/mnemonics-v2/g5-u8fea.webp",
    "label": "启迪",
    "alt": "启迪就是引导人获得新的认识或思考 图中“辶”与“由”按左下包围结构自然长成“迪”。"
  },
  "嫁": {
    "src": "/illustrations/mnemonics-v2/g5-u5ac1.webp",
    "label": "出嫁",
    "alt": "出嫁旧时多指女子结婚后到配偶家庭生活 图中“女”与“家”按左右结构自然长成“嫁”。"
  },
  "缴": {
    "src": "/illustrations/mnemonics-v2/g5-u7f34.webp",
    "label": "缴费",
    "alt": "缴费就是按照规定交付费用 图中“纟”与“敫”按左右结构自然长成“缴”。"
  },
  "榜": {
    "src": "/illustrations/mnemonics-v2/g5-u699c.webp",
    "label": "榜样",
    "alt": "榜样是值得学习和模仿的人或事物 图中“木”与“旁”按左右结构自然长成“榜”。"
  },
  "兼": {
    "src": "/illustrations/mnemonics-v2/g5-u517c.webp",
    "label": "兼职",
    "alt": "兼职是在本职之外还承担另一份工作 图中“兼”按独体结构自然长成“兼”。"
  },
  "嘲": {
    "src": "/illustrations/mnemonics-v2/g5-u5632.webp",
    "label": "嘲笑",
    "alt": "嘲笑是用言语或表情取笑别人，容易伤害他人 图中“口”与“朝”按左右结构自然长成“嘲”。"
  },
  "枕": {
    "src": "/illustrations/mnemonics-v2/g5-u6795.webp",
    "label": "枕头",
    "alt": "枕头是睡觉时垫在头下、支撑头颈的用品 图中“木”与“冘”按左右结构自然长成“枕”。"
  },
  "蚕": {
    "src": "/illustrations/mnemonics-v2/g5-u8695.webp",
    "label": "蚕茧",
    "alt": "蚕是一种会吐丝结茧的昆虫，常以桑叶为食 图中“天”与“虫”按上下结构自然长成“蚕”。"
  },
  "考": {
    "src": "/illustrations/mnemonics-v2/g5-u8003.webp",
    "label": "考试",
    "alt": "考试是用题目或操作检查知识和能力的一种方式 图中“耂”与“丂”按左上包围结构自然长成“考”。"
  },
  "疼": {
    "src": "/illustrations/mnemonics-v2/g5-u75bc.webp",
    "label": "疼爱",
    "alt": "疼爱是关心、爱护；“疼”本身也可表示身体痛 图中“疒”与“冬”按左上包围结构自然长成“疼”。"
  },
  "席": {
    "src": "/illustrations/mnemonics-v2/g5-u5e2d.webp",
    "label": "草席",
    "alt": "草席是用草茎、竹篾等编成、可以铺坐或铺睡的用品 图中“广”与“廿”与“巾”按左上包围结构自然长成“席”。"
  },
  "糖": {
    "src": "/illustrations/mnemonics-v2/g5-u7cd6.webp",
    "label": "糖果",
    "alt": "糖是有甜味的食物成分，也指糖果等甜食 图中“米”与“唐”按左右结构自然长成“糖”。"
  },
  "屑": {
    "src": "/illustrations/mnemonics-v2/g5-u5c51.webp",
    "label": "纸屑",
    "alt": "纸屑是纸张破碎后留下的小片 图中“尸”与“肖”按左上包围结构自然长成“屑”。"
  },
  "钉": {
    "src": "/illustrations/mnemonics-v2/g5-u9489.webp",
    "label": "钉子",
    "alt": "钉子是一端尖、一端有帽，用来固定物体的金属小件 图中“钅”与“丁”按左右结构自然长成“钉”。"
  },
  "毕": {
    "src": "/illustrations/mnemonics-v2/g5-u6bd5.webp",
    "label": "毕业",
    "alt": "毕业表示在学校或训练机构完成规定的学习 图中“比”与“十”按上下结构自然长成“毕”。"
  },
  "煮": {
    "src": "/illustrations/mnemonics-v2/g5-u716e.webp",
    "label": "煮饭",
    "alt": "煮饭是把食物放在水里或锅里加热至熟 图中“者”与“灬”按上下结构自然长成“煮”。"
  },
  "腼": {
    "src": "/illustrations/mnemonics-v2/g5-u817c.webp",
    "label": "腼腆",
    "alt": "腼腆形容因为害羞或不自然而不大方 图中“月”与“面”按左右结构自然长成“腼”。"
  },
  "腆": {
    "src": "/illustrations/mnemonics-v2/g5-u8146.webp",
    "label": "腼腆",
    "alt": "腼腆表示害羞、拘谨，面对别人时不够自然 图中“月”与“典”按左右结构自然长成“腆”。"
  },
  "誊": {
    "src": "/illustrations/mnemonics-v2/g5-u8a8a.webp",
    "label": "誊写",
    "alt": "誊写就是把文字清楚、整齐地重新抄写一遍 图中“龹”与“言”按上下结构自然长成“誊”。"
  },
  "励": {
    "src": "/illustrations/mnemonics-v2/g5-u52b1.webp",
    "label": "鼓励",
    "alt": "鼓励就是用肯定和支持帮助别人增强信心 图中“厉”与“力”按左右结构自然长成“励”。"
  },
  "版": {
    "src": "/illustrations/mnemonics-v2/g5-u7248.webp",
    "label": "出版",
    "alt": "出版是把作品编辑制作成书刊等，提供给读者 图中“片”与“反”按左右结构自然长成“版”。"
  },
  "祥": {
    "src": "/illustrations/mnemonics-v2/g5-u7965.webp",
    "label": "慈祥",
    "alt": "吉祥表示幸运、顺利，是人们对美好生活的祝愿 图中“礻”与“羊”按左右结构自然长成“祥”。"
  },
  "歧": {
    "src": "/illustrations/mnemonics-v2/g5-u6b67.webp",
    "label": "歧途",
    "alt": "歧途是偏离正确方向的道路，也比喻错误的发展方向 图中“止”与“支”按左右结构自然长成“歧”。"
  },
  "谨": {
    "src": "/illustrations/mnemonics-v2/g5-u8c28.webp",
    "label": "谨慎",
    "alt": "谨慎就是做事认真小心，事先想到可能的问题 图中“讠”与“堇”按左右结构自然长成“谨”。"
  },
  "榆": {
    "src": "/illustrations/mnemonics-v2/g5-u6986.webp",
    "label": "榆树",
    "alt": "榆树是一种常见落叶树，木材坚实，果实叫榆钱 图中“木”与“俞”按左右结构自然长成“榆”。"
  },
  "畔": {
    "src": "/illustrations/mnemonics-v2/g5-u7554.webp",
    "label": "河畔",
    "alt": "河畔就是河边靠近水的地方 图中“田”与“半”按左右结构自然长成“畔”。"
  },
  "更": {
    "src": "/illustrations/mnemonics-v2/g5-u66f4.webp",
    "label": "一更",
    "alt": "“一更”是旧时夜间计时的一段，这里读gēng；“更加”中读gèng 图中“更”按独体结构自然长成“更”。"
  },
  "聒": {
    "src": "/illustrations/mnemonics-v2/g5-u8052.webp",
    "label": "聒噪",
    "alt": "聒噪形容声音嘈杂，令人难以安静 图中“耳”与“舌”按左右结构自然长成“聒”。"
  },
  "孙": {
    "src": "/illustrations/mnemonics-v2/g5-u5b59.webp",
    "label": "子孙",
    "alt": "子孙指儿子、孙子等后代 图中“子”与“小”按左右结构自然长成“孙”。"
  },
  "泊": {
    "src": "/illustrations/mnemonics-v2/g5-u6cca.webp",
    "label": "停泊",
    "alt": "停泊就是船靠岸停下；“湖泊”的“泊”读pō 图中“氵”与“白”按左右结构自然长成“泊”。"
  },
  "愁": {
    "src": "/illustrations/mnemonics-v2/g5-u6101.webp",
    "label": "发愁",
    "alt": "发愁就是因为困难或担心而心里不安 图中“秋”与“心”按上下结构自然长成“愁”。"
  },
  "寺": {
    "src": "/illustrations/mnemonics-v2/g5-u5bfa.webp",
    "label": "寺庙",
    "alt": "寺庙是供奉宗教神像、进行相关活动的建筑 图中“土”与“寸”按上下结构自然长成“寺”。"
  },
  "桨": {
    "src": "/illustrations/mnemonics-v2/g5-u6868.webp",
    "label": "船桨",
    "alt": "船桨是划船时拨水推动船前进的工具 图中“丬”与“夕”与“木”按上下结构自然长成“桨”。"
  },
  "桩": {
    "src": "/illustrations/mnemonics-v2/g5-u6869.webp",
    "label": "木桩",
    "alt": "木桩是打入地面、用来固定或支撑物体的木柱 图中“木”与“庄”按左右结构自然长成“桩”。"
  },
  "暇": {
    "src": "/illustrations/mnemonics-v2/g5-u6687.webp",
    "label": "闲暇",
    "alt": "闲暇是没有工作或学习任务、可以自由安排的时间 图中“日”与“叚”按左右结构自然长成“暇”。"
  },
  "榕": {
    "src": "/illustrations/mnemonics-v2/g5-u6995.webp",
    "label": "榕树",
    "alt": "榕树枝叶繁茂，常有从枝条垂下并扎入土中的气生根 图中“木”与“容”按左右结构自然长成“榕”。"
  },
  "纠": {
    "src": "/illustrations/mnemonics-v2/g5-u7ea0.webp",
    "label": "纠正",
    "alt": "纠正就是发现错误后把它改正确 图中“纟”与“丩”按左右结构自然长成“纠”。"
  },
  "耀": {
    "src": "/illustrations/mnemonics-v2/g5-u8000.webp",
    "label": "闪耀",
    "alt": "闪耀就是明亮的光快速跳动、不断显现 图中“光”与“翟”按左右结构自然长成“耀”。"
  },
  "涨": {
    "src": "/illustrations/mnemonics-v2/g5-u6da8.webp",
    "label": "涨潮",
    "alt": "涨潮是海水或江河水面在一定时间内升高 图中“氵”与“张”按左右结构自然长成“涨”。"
  },
  "塔": {
    "src": "/illustrations/mnemonics-v2/g5-u5854.webp",
    "label": "宝塔",
    "alt": "宝塔是层层向上、常有尖顶的高大建筑 图中“土”与“荅”按左右结构自然长成“塔”。"
  },
  "梢": {
    "src": "/illustrations/mnemonics-v2/g5-u68a2.webp",
    "label": "树梢",
    "alt": "树梢是树木枝干最上方或最末端的部分 图中“木”与“肖”按左右结构自然长成“梢”。"
  },
  "眉": {
    "src": "/illustrations/mnemonics-v2/g5-u7709.webp",
    "label": "眉毛",
    "alt": "眉毛是长在眼睛上方的一列毛发 图中“𠃜”与“目”按左上包围结构自然长成“眉”。"
  },
  "抛": {
    "src": "/illustrations/mnemonics-v2/g5-u629b.webp",
    "label": "抛开",
    "alt": "抛开就是用手把东西扔出去，也可比喻暂时放下 图中“扌”与“九”与“力”按左右结构自然长成“抛”。"
  },
  "悄": {
    "src": "/illustrations/mnemonics-v2/g5-u6084.webp",
    "label": "悄没声儿",
    "alt": "“悄没声儿”表示一点声音也没有，这里读qiǎo；“悄悄”中常读qiāo 图中“忄”与“肖”按左右结构自然长成“悄”。"
  },
  "累": {
    "src": "/illustrations/mnemonics-v2/g5-u7d2f.webp",
    "label": "累累",
    "alt": "“累累”在课文中形容接连成串，这里读léi；表示疲劳时读lèi 图中“田”与“糸”按上下结构自然长成“累”。"
  },
  "嫦": {
    "src": "/illustrations/mnemonics-v2/g5-u5ae6.webp",
    "label": "嫦娥",
    "alt": "嫦娥是中国古代神话中居住在月宫的人物 图中“女”与“常”按左右结构自然长成“嫦”。"
  },
  "娥": {
    "src": "/illustrations/mnemonics-v2/g5-u5a25.webp",
    "label": "嫦娥",
    "alt": "嫦娥是中国古代关于月亮的神话人物 图中“女”与“我”按左右结构自然长成“娥”。"
  },
  "嫉": {
    "src": "/illustrations/mnemonics-v2/g5-u5ac9.webp",
    "label": "嫉妒",
    "alt": "嫉妒是看见别人比自己好而产生不舒服甚至怨恨的心理 图中“女”与“疾”按左右结构自然长成“嫉”。"
  },
  "妒": {
    "src": "/illustrations/mnemonics-v2/g5-u5992.webp",
    "label": "嫉妒",
    "alt": "嫉妒会让人只盯着别人的长处，忽略自己的成长 图中“女”与“户”按左右结构自然长成“妒”。"
  },
  "瓷": {
    "src": "/illustrations/mnemonics-v2/g5-u74f7.webp",
    "label": "瓷器",
    "alt": "瓷器是用瓷土制成、经过高温烧制的器物 图中“次”与“瓦”按上下结构自然长成“瓷”。"
  },
  "耻": {
    "src": "/illustrations/mnemonics-v2/g5-u803b.webp",
    "label": "羞耻",
    "alt": "羞耻是意识到自己的错误或不恰当行为时感到惭愧 图中“耳”与“止”按左右结构自然长成“耻”。"
  },
  "识": {
    "src": "/illustrations/mnemonics-v2/g5-u8bc6.webp",
    "label": "默而识之",
    "alt": "“默而识之”中的“识”表示记住，读zhì；表示认识时读shí 图中“讠”与“只”按左右结构自然长成“识”。"
  },
  "寝": {
    "src": "/illustrations/mnemonics-v2/g5-u5bdd.webp",
    "label": "就寝",
    "alt": "就寝就是上床睡觉 图中“宀”与“丬”与“彐”与“冖”与“又”按上下结构自然长成“寝”。"
  },
  "矣": {
    "src": "/illustrations/mnemonics-v2/g5-u77e3.webp",
    "label": "矣",
    "alt": "矣是文言语气词，常放在句末，表示肯定、完成或感叹 图中“厶”与“矢”按上下结构自然长成“矣”。"
  },
  "岂": {
    "src": "/illustrations/mnemonics-v2/g5-u5c82.webp",
    "label": "岂能",
    "alt": "岂能表示反问，相当于“怎么能”“难道能” 图中“山”与“己”按上下结构自然长成“岂”。"
  },
  "诲": {
    "src": "/illustrations/mnemonics-v2/g5-u8bf2.webp",
    "label": "教诲",
    "alt": "教诲是长辈或老师耐心地教导 图中“讠”与“每”按左右结构自然长成“诲”。"
  },
  "谓": {
    "src": "/illustrations/mnemonics-v2/g5-u8c13.webp",
    "label": "所谓",
    "alt": "所谓表示所说的、所指的内容 图中“讠”与“胃”按左右结构自然长成“谓”。"
  },
  "诵": {
    "src": "/illustrations/mnemonics-v2/g5-u8bf5.webp",
    "label": "诵读",
    "alt": "诵读就是有声音、有节奏地朗读或背读 图中“讠”与“甬”按左右结构自然长成“诵”。"
  },
  "舅": {
    "src": "/illustrations/mnemonics-v2/g5-u8205.webp",
    "label": "舅舅",
    "alt": "舅舅是母亲的兄弟 图中“臼”与“男”按上下结构自然长成“舅”。"
  },
  "宴": {
    "src": "/illustrations/mnemonics-v2/g5-u5bb4.webp",
    "label": "宴会",
    "alt": "宴会是多人聚在一起吃饭、庆祝或交流的活动 图中“宀”与“妟”按上下结构自然长成“宴”。"
  },
  "斩": {
    "src": "/illustrations/mnemonics-v2/g5-u65a9.webp",
    "label": "斩断",
    "alt": "斩断就是用利器把连接的东西砍断 图中“车”与“斤”按左右结构自然长成“斩”。"
  },
  "凯": {
    "src": "/illustrations/mnemonics-v2/g5-u51ef.webp",
    "label": "凯旋",
    "alt": "凯旋指军队获胜归来，也泛指胜利归来 图中“岂”与“几”按左右结构自然长成“凯”。"
  },
  "葛": {
    "src": "/illustrations/mnemonics-v2/g5-u845b.webp",
    "label": "葛布",
    "alt": "葛是一种藤本植物，葛布可以用它的纤维织成 图中“艹”与“曷”按上下结构自然长成“葛”。"
  },
  "述": {
    "src": "/illustrations/mnemonics-v2/g5-u8ff0.webp",
    "label": "讲述",
    "alt": "讲述就是把事情有次序地说出来 图中“辶”与“术”按左下包围结构自然长成“述”。"
  },
  "传": {
    "src": "/illustrations/mnemonics-v2/g5-u4f20.webp",
    "label": "传记",
    "alt": "“传记”中的“传”读zhuàn，指记述人物经历的文章；“传递”中读chuán 图中“亻”与“专”按左右结构自然长成“传”。"
  },
  "鲁": {
    "src": "/illustrations/mnemonics-v2/g5-u9c81.webp",
    "label": "鲁莽",
    "alt": "鲁莽形容说话做事不细想，行动冒失 图中“鱼”与“日”按上下结构自然长成“鲁”。"
  },
  "煞": {
    "src": "/illustrations/mnemonics-v2/g5-u715e.webp",
    "label": "煞气",
    "alt": "煞气在故事语境中指凶恶、逼人的气势 图中“刍”与“攵”与“灬”按上下结构自然长成“煞”。"
  },
  "寇": {
    "src": "/illustrations/mnemonics-v2/g5-u5bc7.webp",
    "label": "敌寇",
    "alt": "敌寇是侵犯别国或别处的敌人 图中“宀”与“元”与“攴”按上下结构自然长成“寇”。"
  },
  "贾": {
    "src": "/illustrations/mnemonics-v2/g5-u8d3e.webp",
    "label": "商贾",
    "alt": "商贾是旧时对商人的称呼，这里的“贾”读gǔ；作为姓氏时读jiǎ 图中“覀”与“贝”按上下结构自然长成“贾”。"
  },
  "卷": {
    "src": "/illustrations/mnemonics-v2/g5-u5377.webp",
    "label": "试卷",
    "alt": "“试卷”中的“卷”读juàn，指成套的考试纸；“卷起”中读juǎn 图中“龹”与“㔾”按上下结构自然长成“卷”。"
  },
  "刊": {
    "src": "/illustrations/mnemonics-v2/g5-u520a.webp",
    "label": "刊物",
    "alt": "刊物是定期或不定期出版的杂志、报纸等读物 图中“干”与“刂”按左右结构自然长成“刊”。"
  },
  "琐": {
    "src": "/illustrations/mnemonics-v2/g5-u7410.webp",
    "label": "琐事",
    "alt": "琐事是细小、零碎的事情 图中“王”与“⺌”与“贝”按左右结构自然长成“琐”。"
  },
  "呻": {
    "src": "/illustrations/mnemonics-v2/g5-u547b.webp",
    "label": "呻吟",
    "alt": "呻吟是因为痛苦或不适而发出的低沉声音 图中“口”与“申”按左右结构自然长成“呻”。"
  },
  "某": {
    "src": "/illustrations/mnemonics-v2/g5-u67d0.webp",
    "label": "某人",
    "alt": "某人表示没有说出或不需要说出姓名的一个人 图中“甘”与“木”按上下结构自然长成“某”。"
  },
  "津": {
    "src": "/illustrations/mnemonics-v2/g5-u6d25.webp",
    "label": "天津",
    "alt": "天津是中国的直辖市；“津”也可指渡口或唾液 图中“氵”与“聿”按左右结构自然长成“津”。"
  },
  "限": {
    "src": "/illustrations/mnemonics-v2/g5-u9650.webp",
    "label": "限制",
    "alt": "限制就是规定范围，不让数量、时间或行动超过界线 图中“阝”与“艮”按左右结构自然长成“限”。"
  },
  "统": {
    "src": "/illustrations/mnemonics-v2/g5-u7edf.webp",
    "label": "统一",
    "alt": "统一就是把分散的事物合在共同标准或整体之中 图中“纟”与“充”按左右结构自然长成“统”。"
  },
  "朴": {
    "src": "/illustrations/mnemonics-v2/g5-u6734.webp",
    "label": "朴实",
    "alt": "朴实形容不浮夸，真实自然 图中“木”与“卜”按左右结构自然长成“朴”。"
  },
  "喻": {
    "src": "/illustrations/mnemonics-v2/g5-u55bb.webp",
    "label": "比喻",
    "alt": "比喻是用有相似点的事物来说明另一个事物 图中“口”与“俞”按左右结构自然长成“喻”。"
  },
  "差": {
    "src": "/illustrations/mnemonics-v2/g5-u5dee.webp",
    "label": "差事",
    "alt": "“差事”指被派去做的任务，这里读chāi；“差别”读chā，“较差”读chà 图中“⺶”与“工”按左上包围结构自然长成“差”。"
  },
  "瘾": {
    "src": "/illustrations/mnemonics-v2/g5-u763e.webp",
    "label": "上瘾",
    "alt": "上瘾表示对某种事物形成难以控制、总想继续的依赖 图中“疒”与“隐”按左上包围结构自然长成“瘾”。"
  },
  "奔": {
    "src": "/illustrations/mnemonics-v2/g5-u5954.webp",
    "label": "奔向",
    "alt": "“奔向”表示急速朝某处去，这里读bēn；“投奔”中读bèn 图中“大”与“卉”按上下结构自然长成“奔”。"
  },
  "籍": {
    "src": "/illustrations/mnemonics-v2/g5-u7c4d.webp",
    "label": "书籍",
    "alt": "书籍是装订成册、记录文字或图画的读物 图中“⺮”与“耤”按上下结构自然长成“籍”。"
  },
  "饥": {
    "src": "/illustrations/mnemonics-v2/g5-u9965.webp",
    "label": "饥饿",
    "alt": "饥饿是身体因为缺少食物而产生的需要进食的感觉 图中“饣”与“几”按左右结构自然长成“饥”。"
  },
  "偿": {
    "src": "/illustrations/mnemonics-v2/g5-u507f.webp",
    "label": "补偿",
    "alt": "补偿是用金钱、物品或行动弥补别人的损失 图中“亻”与“尝”按左右结构自然长成“偿”。"
  },
  "甸": {
    "src": "/illustrations/mnemonics-v2/g5-u7538.webp",
    "label": "沉甸甸",
    "alt": "沉甸甸形容东西很重、向下坠的样子 图中“勹”与“田”按右上包围结构自然长成“甸”。"
  },
  "悟": {
    "src": "/illustrations/mnemonics-v2/g5-u609f.webp",
    "label": "领悟",
    "alt": "领悟就是经过思考后明白其中的意思或道理 图中“忄”与“吾”按左右结构自然长成“悟”。"
  },
  "馈": {
    "src": "/illustrations/mnemonics-v2/g5-u9988.webp",
    "label": "反馈",
    "alt": "反馈是把结果、意见或信息返回给对方 图中“饣”与“贵”按左右结构自然长成“馈”。"
  },
  "磁": {
    "src": "/illustrations/mnemonics-v2/g5-u78c1.webp",
    "label": "磁铁",
    "alt": "磁铁能吸引铁、镍等材料，也有南北两个磁极 图中“石”与“兹”按左右结构自然长成“磁”。"
  },
  "酵": {
    "src": "/illustrations/mnemonics-v2/g5-u9175.webp",
    "label": "发酵",
    "alt": "发酵是微生物作用使食物等发生变化的过程 图中“酉”与“孝”按左右结构自然长成“酵”。"
  },
  "皎": {
    "src": "/illustrations/mnemonics-v2/g5-u768e.webp",
    "label": "皎洁",
    "alt": "皎洁形容月光明亮而洁白 图中“白”与“交”按左右结构自然长成“皎”。"
  },
  "鉴": {
    "src": "/illustrations/mnemonics-v2/g5-u9274.webp",
    "label": "鉴赏",
    "alt": "鉴赏就是通过观察和思考来辨别、欣赏作品的特点和价值 图中“〢”与“丿”与“一”与“丶”与“金”按上下结构自然长成“鉴”。"
  },
  "沥": {
    "src": "/illustrations/mnemonics-v2/g5-u6ca5.webp",
    "label": "呕心沥血",
    "alt": "呕心沥血比喻费尽心思和精力 图中“氵”与“历”按左右结构自然长成“沥”。"
  }
} as const;

/* Generated by scripts/generate-grade5-catalog.mjs. Do not edit by hand. */
export const grade5LessonVisuals = {
  "g5v1-l01": {
    "src": "/illustrations/lessons/g5-01.webp",
    "label": "白鹭",
    "alt": "清晨水田里的白鹭，留白宁静，羽毛与芦苇形成优雅节奏"
  },
  "g5v1-l02": {
    "src": "/illustrations/lessons/g5-02.webp",
    "label": "落花生",
    "alt": "暖秋小院里一家人围坐谈花生，泥土、果实和灯火温厚朴素"
  },
  "g5v1-l03": {
    "src": "/illustrations/lessons/g5-03.webp",
    "label": "桂花雨",
    "alt": "桂树下金色花雨纷飞，孩子抱树摇花，竹箩放在一旁，江南庭院温柔明亮"
  },
  "g5v1-l04": {
    "src": "/illustrations/lessons/g5-04.webp",
    "label": "珍珠鸟",
    "alt": "书房窗边的珍珠鸟靠近少年，藤蔓与阳光营造安静信赖感"
  },
  "g5v1-l05": {
    "src": "/illustrations/lessons/g5-05.webp",
    "label": "搭石",
    "alt": "山村清溪上的搭石，乡亲相让而行，水光清澈、动作有秩序"
  },
  "g5v1-l06": {
    "src": "/illustrations/lessons/g5-06.webp",
    "label": "将相和",
    "alt": "古代宫廷与城门之间，两位人物从对峙走向并肩，庄重但儿童友好"
  },
  "g5v1-l07": {
    "src": "/illustrations/lessons/g5-07.webp",
    "label": "什么比猎豹的速度更快",
    "alt": "横向速度赛道从猎豹延伸到火箭和光束，层级清楚、科学明快"
  },
  "g5v1-l08": {
    "src": "/illustrations/lessons/g5-08.webp",
    "label": "冀中的地道战",
    "alt": "剖面式地道网络连接村庄，通风口、岔道和民众协作清晰可见"
  },
  "g5v1-l09": {
    "src": "/illustrations/lessons/g5-09.webp",
    "label": "猎人海力布",
    "alt": "山谷村庄前，猎人警告乡亲远离灾害，神话气息而不惊悚"
  },
  "g5v1-l10": {
    "src": "/illustrations/lessons/g5-10.webp",
    "label": "牛郎织女（一）",
    "alt": "月夜田野里青年与老牛相伴，远处织机星光，民间故事温暖梦幻"
  },
  "g5v1-l11": {
    "src": "/illustrations/lessons/g5-11.webp",
    "label": "牛郎织女（二）",
    "alt": "星河之上鹊桥相连，两端人物遥望，蓝紫夜空柔和而有希望"
  },
  "g5v1-l12": {
    "src": "/illustrations/lessons/g5-12.webp",
    "label": "古诗三首",
    "alt": "古卷上叠映山河、风雨与晨光，三幅诗境彼此呼应、含蓄庄重"
  },
  "g5v1-l13": {
    "src": "/illustrations/lessons/g5-13.webp",
    "label": "少年中国说（节选）",
    "alt": "少年迎着朝阳站在山河前，鹰、江流与星光组成昂扬的象征画面"
  },
  "g5v1-l14": {
    "src": "/illustrations/lessons/g5-14.webp",
    "label": "圆明园的毁灭",
    "alt": "画面一半是园林盛景、一半是冷静的残垣剪影，克制表达历史损失"
  },
  "g5v1-l15": {
    "src": "/illustrations/lessons/g5-15.webp",
    "label": "小岛",
    "alt": "海防小岛上的菜地与营房，战士分享饭菜，海风强劲但画面温暖"
  },
  "g5v1-l16": {
    "src": "/illustrations/lessons/g5-16.webp",
    "label": "太阳",
    "alt": "太阳光线连接地球上的水循环、植物与生活，儿童科学信息图风格"
  },
  "g5v1-l17": {
    "src": "/illustrations/lessons/g5-17.webp",
    "label": "松鼠",
    "alt": "森林树杈上的松鼠与巢穴，尾巴蓬松，观察细节丰富而自然"
  },
  "g5v1-l18": {
    "src": "/illustrations/lessons/g5-18.webp",
    "label": "慈母情深",
    "alt": "旧厂房柔光中母亲伏案工作，孩子握着书，真实克制、不苦情化"
  },
  "g5v1-l19": {
    "src": "/illustrations/lessons/g5-19.webp",
    "label": "父爱之舟",
    "alt": "江南夜色中的小船载着父子和书箱，灯火映水，回忆感温柔含蓄"
  },
  "g5v1-l20": {
    "src": "/illustrations/lessons/g5-20.webp",
    "label": "“精彩极了”和“糟糕透了”",
    "alt": "书桌两侧是温暖鼓励与冷静提醒，中间孩子修改作品，平衡而积极"
  },
  "g5v1-l21": {
    "src": "/illustrations/lessons/g5-21.webp",
    "label": "古诗词三首",
    "alt": "秋山、江船与雪夜驿帐组成三联诗境，月色贯穿，清雅安静"
  },
  "g5v1-l22": {
    "src": "/illustrations/lessons/g5-22.webp",
    "label": "鸟的天堂",
    "alt": "巨大的榕树垂根成林，晨光里群鸟飞起，小船从水面经过"
  },
  "g5v1-l23": {
    "src": "/illustrations/lessons/g5-23.webp",
    "label": "月迹",
    "alt": "中秋庭院里孩子追寻月影，瓷盆、水面和树梢层层映月"
  },
  "g5v1-l24": {
    "src": "/illustrations/lessons/g5-24.webp",
    "label": "古人谈读书",
    "alt": "古今书桌相连，孩子专心读书做笔记，眼到口到心到以图形呈现"
  },
  "g5v1-l25": {
    "src": "/illustrations/lessons/g5-25.webp",
    "label": "忆读书",
    "alt": "书页化成时间长河，童年到老年的阅读剪影相连，明亮亲切"
  },
  "g5v1-l26": {
    "src": "/illustrations/lessons/g5-26.webp",
    "label": "我的“长生果”",
    "alt": "知识树结出发光书果，孩子阅读时故事世界从书页生长出来"
  }
} as const;
