/* Generated by scripts/generate-miniprogram-catalog.mjs. Do not edit. */
export const catalogSchemaVersion = 2;
export const catalogContentVersion = "10f65938ec1fe423";
export const catalogOrigin = "https://knowing-word.jbang2004.chatgpt.site";
export const skillDimensions = ["recognition","phonology","semantics","generation","discrimination","context"] as const;
export const learningTrackIds = ["words","structure","split","honglan"] as const;
export const trackOrigins = {"words":"识字小测","structure":"空间结构","split":"拆一拆","honglan":"红蓝字"} as const;
